# -*- coding: utf-8 -*-
"""Modulares Paket fuer das AI-Streaming (MSM Agentic Engine)."""

# Externe Services fuer Abwaertskompatibilitaet und Monkeypatching
from services.openai_compatible_adapter import (
    MAX_REASONING_CHARS,
    MAX_STREAM_SECONDS,
    AiProviderRequestError,
    StreamUsage,
    stream_chat_completion,
    usage_addieren,
)
from services.ai_usage_service import (
    AiQuotaExceeded,
    AiUsageConflict,
    abrechnung,
    complete_ai_usage,
    fail_ai_usage,
    reserve_ai_usage,
)
from services.ai_action_service import execute_read_tool
from services.ai_context_service import anlagenwissen_nachtrag
from services import (
    ai_attachment_service,
    ai_guardian_repair_service,
    ai_guardian_report,
    ai_guardian_service,
    ai_meldestelle,
    ai_model_catalog,
    ai_provider_service,
    ai_reasoning,
    ai_run_broker,
    ai_run_service,
    ai_task_report,
    audit_service,
    desktop_job_service,
)

from services.ai_stream.types import (
    BILDFELD,
    BILD_VERBRAUCHT,
    GESETZTE_FELDER,
    KEIN_BLICK_GRUND,
    MAX_GLEICHE_AUFRUFE,
    MAX_GLEICHE_POLLING_AUFRUFE,
    MAX_TOOL_CALLS,
    MAX_TOOL_RESULT_CHARS_PER_ROUND,
    MAX_TOOL_ROUNDS,
    MAX_WRITE_ROUNDS,
    MELDUNGSMARKE,
    POLLING_WERKZEUGE,
    WERKZEUG_ZEITGRENZE,
    _FREITEXT_WERKZEUGE,
    _ANLAUF_SCHLEIFE,
    _ANLAUF_SCHLOESSER,
    _ANLAUF_SCHRANKE,
    _ANLAUF_WARTENDE,
    GuardianRahmenUnlesbar,
    _Anlauf,
    _FragenErgebnis,
    _SchreibrundenErgebnis,
    _Vorbereitung,
    _WartenErgebnis,
)

from services.ai_stream.context import (
    _denken_am_modell,
    _modell_fuer,
    _rolle_ableiten,
    aufgabe_aus_zustand,
    familie_aus_zustand,
    guardian_aus_zustand,
    herkunft_aus_zustand,
    rolle_aus_zustand,
    worker_aus_zustand,
)

from services.ai_stream.read_tools import (
    _ablehnung_protokollieren,
    _anzeigeeintrag,
    _aufrufnachricht,
    _aussortieren,
    _ergebnis_schwaerzen,
    _leserunde_ausfuehren,
    _lesezugriffe_protokollieren,
    _rundenfehler_nachrichten,
    _runde_zaehlen,
    _serverbezug,
    _servernummer,
    _tool_followup_messages,
    _werkzeug_ausfuehren,
    _werkzeug_nebenlaeufigkeit,
    _werkzeuge_ansagen,
)

from services.ai_stream.write_tools import (
    _aktionsmeldung,
    _ask_formfehler_messages,
    _ask_refusal_messages,
    _freigabe_melden,
    _freigabe_per_mail_erbeten,
    _persist_write_proposals,
    _schreibrunde_ausfuehren,
    _vorschlag_ergebnisse,
    _vorschlag_ereignis,
    _vorschlaege_zuruecknehmen,
    _write_followup_messages,
)

from services.ai_stream.interactions import (
    _alte_bilder_entwerten,
    _bilder_herausloesen,
    _desktop_argumente,
    _desktop_behandeln,
    _desktopmeldung,
    _fragen_behandeln,
    _sieht_nicht,
    _warten_behandeln,
)

from services.ai_stream.lifecycle import (
    _abschnitt_fuer_ablage,
    _bericht_zustellen,
    _finalize_stream,
    _lauf_abschliessen,
    _lauf_nachbereiten,
    _runde_filtern,
    _segment_anlaufen,
    _segment_beginnen,
    _segment_vorbereiten,
    _werkzeug_signatur,
    _werkzeuge_und_grenze,
)

from services.ai_stream.launcher import (
    _anlauf_im_thread,
    _anlauf_nebenlaeufigkeit,
    _anlaufrecht,
    lauf_beginnen,
    lauf_beginnen_nebenher,
)

from services.ai_stream.engine import segment_ausfuehren

__all__ = [
    # Externe Services & Utilities
    "stream_chat_completion",
    "MAX_REASONING_CHARS",
    "MAX_STREAM_SECONDS",
    "AiProviderRequestError",
    "StreamUsage",
    "usage_addieren",
    "reserve_ai_usage",
    "complete_ai_usage",
    "fail_ai_usage",
    "abrechnung",
    "AiQuotaExceeded",
    "AiUsageConflict",
    "execute_read_tool",
    "anlagenwissen_nachtrag",
    "ai_run_broker",
    "ai_run_service",
    "ai_provider_service",
    "ai_model_catalog",
    "ai_reasoning",
    "ai_attachment_service",
    "ai_guardian_service",
    "audit_service",
    "desktop_job_service",
    "ai_task_report",
    "ai_guardian_report",
    "ai_guardian_repair_service",
    "ai_meldestelle",
    # Konstanten
    "MAX_TOOL_RESULT_CHARS_PER_ROUND",
    "MAX_TOOL_CALLS",
    "MAX_TOOL_ROUNDS",
    "MAX_WRITE_ROUNDS",
    "WERKZEUG_ZEITGRENZE",
    "MAX_GLEICHE_AUFRUFE",
    "MAX_GLEICHE_POLLING_AUFRUFE",
    "POLLING_WERKZEUGE",
    "_FREITEXT_WERKZEUGE",
    "GESETZTE_FELDER",
    "BILDFELD",
    "BILD_VERBRAUCHT",
    "MELDUNGSMARKE",
    "KEIN_BLICK_GRUND",
    "_ANLAUF_SCHLEIFE",
    "_ANLAUF_SCHLOESSER",
    "_ANLAUF_SCHRANKE",
    "_ANLAUF_WARTENDE",
    # Typen & Fehler
    "GuardianRahmenUnlesbar",
    "_Vorbereitung",
    "_Anlauf",
    "_FragenErgebnis",
    "_SchreibrundenErgebnis",
    "_WartenErgebnis",
    # Kontext & Zustand
    "guardian_aus_zustand",
    "aufgabe_aus_zustand",
    "rolle_aus_zustand",
    "herkunft_aus_zustand",
    "familie_aus_zustand",
    "worker_aus_zustand",
    "_modell_fuer",
    "_denken_am_modell",
    "_rolle_ableiten",
    # Lese-Werkzeuge
    "_serverbezug",
    "_ergebnis_schwaerzen",
    "_werkzeug_nebenlaeufigkeit",
    "_servernummer",
    "_werkzeuge_ansagen",
    "_anzeigeeintrag",
    "_werkzeug_ausfuehren",
    "_aufrufnachricht",
    "_rundenfehler_nachrichten",
    "_runde_zaehlen",
    "_aussortieren",
    "_tool_followup_messages",
    "_lesezugriffe_protokollieren",
    "_ablehnung_protokollieren",
    "_leserunde_ausfuehren",
    # Schreib-Werkzeuge & Vorschlaege
    "_vorschlag_ereignis",
    "_persist_write_proposals",
    "_vorschlaege_zuruecknehmen",
    "_freigabe_melden",
    "_freigabe_per_mail_erbeten",
    "_ask_refusal_messages",
    "_ask_formfehler_messages",
    "_write_followup_messages",
    "_vorschlag_ergebnisse",
    "_aktionsmeldung",
    "_schreibrunde_ausfuehren",
    # Interaktionen & Desktop
    "_fragen_behandeln",
    "_warten_behandeln",
    "_desktop_argumente",
    "_desktop_behandeln",
    "_bilder_herausloesen",
    "_desktopmeldung",
    "_alte_bilder_entwerten",
    "_sieht_nicht",
    # Lebenszyklus
    "_abschnitt_fuer_ablage",
    "_finalize_stream",
    "_segment_beginnen",
    "_segment_vorbereiten",
    "_lauf_abschliessen",
    "_lauf_nachbereiten",
    "_bericht_zustellen",
    "_werkzeug_signatur",
    "_segment_anlaufen",
    "_werkzeuge_und_grenze",
    "_runde_filtern",
    # Launcher
    "lauf_beginnen",
    "_anlauf_nebenlaeufigkeit",
    "_anlaufrecht",
    "_anlauf_im_thread",
    "lauf_beginnen_nebenher",
    # Engine
    "segment_ausfuehren",
]
