/**
 * Die Landmaske für die Erde des Schwarms: 256 × 128 Zellen, ein Bit je Zelle.
 *
 * Zeilenweise von Nord nach Süd, jede Zeile von 180° West nach Osten — also
 * dieselbe Anordnung wie eine Weltkarte in Plattkarte. Gewonnen aus
 * `frontend/public/earth/blue-marble.jpg` (NASA, gemeinfrei): Flächenmittel je
 * Zelle, Land ist, was nicht vorwiegend blau ist, dazu Eis.
 *
 * **Warum ein Bitfeld und kein Bild.** Die Figur soll ohne Netz und ohne
 * `img.decode()` auskommen: ein Fenster, das gerade nicht malt, dekodiert kein
 * Bild — die Erde bliebe im versteckten Overlay leer. 4 KB Bits sind schneller
 * gelesen als jedes JPEG, und sie reisen im selben nachgeladenen Paket wie der
 * Zeichner.
 */

const BREITE = 256
const HOEHE = 128

const DATEN =
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB//AAf/6AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR//j/////4AAAAAAAAAAAA' +
  'EAAAAAAAAAAAAAAAAAAAB+/gP////8AAAACAAAAAAAAeAAAAAAAAAAAAAAAAAIAAD4H/////gAAAGAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAYAAABAP////+AAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAUQQZ4AAf///8AAAAAAAAAgAAD//wAAOAAAAAAAAAAAwAAA' +
  'AAAA////gAAAAAAAAAAAB///AAAAAAAAAAAAAAHv2GjMQAB///0AAAAAAAACAGM/////8A/gAAAAAAAAAAf8CH/wAA//+QAA' +
  'AAAAAAEA///////z//uAAAAP/6AcAf4ECD4AD//8AAAAAfwAAAD///////////AggB/////8CCecDwAP/4AAAAAP/+AH/3//' +
  '///////////wB/////////gP4D//AAAAAD//eL///////////////xw/////////wB8AH/AAvAAAfj8H////////////////' +
  'AAP///////8QB8AP4ABgAAD8f5////////////////4AP////////AAAAAfAAAAAA/D////////////////3+AA//v/////4' +
  'AHgAAYAAAAAP8P///////////////gfAAAfgB/////AAfAAAAAAAAA/4B//////////////MEAAAAMAAf///+AB+YAAAAAAA' +
  'APB/////////////8ABgAAAAAAA////+AD/wAAAAAAwAcH/////////////AAPAAAAAAAB/////Af/gAAAAABAIB////////' +
  '/////4AB4AAAAAAAD/////j//gAAAAAyAwv/////////////gAHAAAAAAAAH/////P//AAAAAGeP///////////////8AYAA' +
  'AAAAAAP///////wAAAAAB5////////////////QAAAAAAAAAAP//////AAAAAAAAf///////////////9AAAAAAAAAAAf///' +
  '//7BwAAAAAH////////////////gAAAAAAAAAAD////f/8AAAAAAAf///////////////8AAAAAAAAAAAP//////4AAAAAAB' +
  '/7/4n+f/////////gAAAAAAAAAAA////+/4AAAAAAAH9n/APz/////////8EAAAAAAAAAAD//////AAAAAAAP8DH8APH////' +
  '////+AQAAAAAAAAAAP/////4AAAAAAA/gGPxg+P////////wAAAAAAAAAAAA/////+AAAAAAAD8CEx//4///////++AIAAAA' +
  'AAAAAAD/////wAAAAAAAPwABH//j///////4YAAAAAAAAAAAAH/////AAAAAAAA+ACAP/+P///////wwEAAAAAAAAAAAP///' +
  '/8AAAAAAAAD/AAA/////////+DBwAAAAAAAAAAAf////gAAAAAAAH/8AAD/////////4AIAAAAAAAAAAAAf///4AAAAAAAA/' +
  '/wAAf/////////4AAAAAAAAAAAAAB////AAAAAAAAH//48B//////////gAAAAAAAAAAAAAA//+cAAAAAAAAf///////////' +
  '///+AAAAAAAAAAAAAAD/8AQAAAAAAAD//////8////////4AAAAAAAAAAAAAAT/gAgAAAAAAAf////9/4////////AAAAAAA' +
  'AAAAAAAAv+ACAAAAAAAD/////z/wf//////4AAAAAAAAAAAAAAAPwAAAAAAAAAf/////n/kA//////AAAAAAAAAAAAAAAAfA' +
  'AAAAAAAAB/////+P/8B/////4AAAAAAAAAAAAAAAB8AAgAAAAAAP/////8//wD////8AAAAAAAAAAAAAAAAH4MBAAAAAAA//' +
  '////x/+AH/w/8AAAAAAAAAAAAAAAAAPxwA4AAAAAB//////n/4AP8B/gAAAAAAAAAAAAAAAAAP+AAAAAAAAH/////+P/AA/g' +
  'H/ACAAAAAAAAAAAAAAAAN4AAAAAAAA//////8fgAD8Af8AIAAAAAAAAAAAAAAAAB8AAAAAAAD//////54AAHgAP4AAAAAAAA' +
  'AAAAAAAAAABwAAAAAAAP//////2AAAeAAvwAAAAAAAAAAAAAAAAAABAAAAAAAA///////gAAA4ACeAAAAAAAAAAAAAAAAAAA' +
  'EB4AAAAAA//////+cAADgAAwAAAAAAAAAAAAAAAAAAAAP/gAAAAB///////wAAEAAgAAAAAAAAAAAAAAAAAAAAB//AAAAAH/' +
  '//////AAAEAAAADAAAAAAAAAAAAAAAAAAH/+AAAAAH+f////4AAAQAAAAIAAAAAAAAAAAAAAAAAAf//AAAAAIA/////AAAAA' +
  'AIAwAAAAAAAAAAAAAAAAAAB///AAAAAAAf///8AAAAAEgHAAAAAAAAAAAAAAAAAAAH//+AAAAAAB////AAAAAANB8AAAAAAA' +
  'AAAAAAAAAAAA///8AAAAAAH///4AAAAAAcPwAAAAAAAAAAAAAAAAAAH///wAAAAAAf///AAAAAAAw+AAAAAAAAAAAAAAAAAA' +
  'Af///wAAAAAB///4AAAAAADB5AIAAAAAAAAAAAAAAAAB////8AAAAAD///AAAAAAAGBCAHgAAAAAAAAAAAAAAAP////4AAAA' +
  'AH//8AAAAAAAIAAAPgAAAAAAAAAAAAAAAf////4AAAAAf//wAAAAAAAAAAAfAAAAAAAAAAAAAAAA/////gAAAAA///AAAAAA' +
  'AAOAAD6AAAAAAAAAAAAAAAD////+AAAAAD//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAH////wAAAAAP//4AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAf///+AAAAAA///gAAAAAAAAAAAAAAAAAAAAAAAAAAAA////wAAAAAH//+AAAAAAAAAAHhAAAAAAAAAAAAAAA' +
  'AD////AAAAAAf//4MAAAAAAAAG8GAAAAAAAAAAAAAAAAD///8AAAAAB///DgAAAAAAAAf8YAAAAAAAAAAAAAAAAH///wAAAA' +
  'AH//4OAAAAAAAAH/7wAAAAAAAAAAAAAAAAP///AAAAAAf/+A4AAAAAAAAf//AAAAAAAAAAAAAAAAA///4AAAAAA//4DAAAAA' +
  'AAAP//+AAAAAAAAAAAAAAAAD///gAAAAAD//gcAAAAAAAD///8AAAAAAAAAAAAAAAAP//wAAAAAAP/+BwAAAAAAAf///4AAA' +
  'AAAAAAAAAAAAA//8AAAAAAA//4GAAAAAAAB////wAAAAAAAAAAAAAAAD//gAAAAAAB/+AAAAAAAAAH////gAAAAAAAAAAAAA' +
  'AAP/+AAAAAAAH/4AAAAAAAAAf///+AAAAAAAAAAAAAAAB//4AAAAAAAP/gAAAAAAAAA////4AAAAAAAAAAAAAAAH//AAAAAA' +
  'AA/8AAAAAAAAAD////gAAAAAAAAAAAAAAAf/4AAAAAAAB/gAAAAAAAAAP/P/8AAAAAAAAAAAAAAAB//AAAAAAAAH8AAAAAAA' +
  'AAAfAP/wAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAAABgAP+AAAAAAAAAAAAAAAAf/AAAAAAAAAAAAAAAAAAAAAAAf4AAA' +
  'AAAAAAAAAAAAD/4AAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAA' +
  'AA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHwAAAAAAA' +
  'AAAAAAAAAAAAAAAAAIAAIAAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAYAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8AAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAADgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAPgAAGX/nh/+AAAAAAAAAAAAAAAAAAeAAAAAAA' +
  'AAAAAP//gH///////+AAAAAAAAAAAAAAAA34AAAAAAAAAAfv///5/////////4AAAAAAAAAAAAAAH/gAAAAAf///////////' +
  '/////////gAAAAAAAAAB8AAP+AAAAAf/////////////////////gAAAAAADAAH/8//4AAAAf/////////////////////wA' +
  'AAAAf/////////gAAAP/////////////////////8AAAAA///////////4AAH//////////////////////wAIAB////////' +
  '/////wH/////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////' +
  '////////////////////////////////////////////////////////////////////////////////////////////////' +
  '/////////////////////////////////////////////////////////////////////////////////////w=='

let bits = null

function entpackt() {
  if (!bits) {
    const roh = atob(DATEN)
    bits = new Uint8Array(roh.length)
    for (let i = 0; i < roh.length; i += 1) bits[i] = roh.charCodeAt(i)
  }
  return bits
}

/** Ob an dieser Stelle Land ist. Breite und Länge in Grad. */
export function isLand(latitude, longitude) {
  const x = Math.floor((((longitude + 180) % 360 + 360) % 360) / 360 * BREITE) % BREITE
  const y = Math.min(HOEHE - 1, Math.max(0, Math.floor((90 - latitude) / 180 * HOEHE)))
  const index = y * BREITE + x
  return (entpackt()[index >> 3] >> (7 - (index & 7))) & 1
}
