import { createContext, useContext, useEffect, type ReactNode } from 'react'
import { useQuery } from '@tanstack/react-query'
import { languageApi, serversApi } from '@/lib/api'

export type UiLanguage = 'en' | 'de'

const UI_COPY = {
  en: {
    appName: 'Conan Exiles Manager',
    setupUnavailable: 'Unable to connect to the panel. Please check the server is running.',
    pageTitles: {
      dashboard: 'Dashboard',
      servers: 'Server Management',
      backups: 'Backups',
      autorestart: 'Auto-Restarts',
      console: 'Live Console',
      mods: 'Mods',
      config: 'Config Center',
      files: 'File Manager',
      users: 'Users',
      account: 'Account',
    },
    nav: {
      dashboard: 'Dashboard',
      servers: 'Servers',
      backups: 'Backups',
      autorestart: 'Auto-Restarts',
      mods: 'Mods',
      console: 'Console',
      files: 'File Manager',
      config: 'Config Center',
      users: 'Users',
    },
    navSections: {
      overview: 'Overview',
      operations: 'Operations',
      maintenance: 'Maintenance',
      administration: 'Administration',
    },
    account: {
      signOut: 'Sign out',
      logoutFailed: 'Logout failed. Please try again.',
      expandSidebar: 'Expand sidebar',
      collapseSidebar: 'Collapse sidebar',
      account: 'Account',
    },
    branding: {
      byline: 'Built by MauntingStudios',
      company: 'MauntingStudios',
      website: 'Website',
      passwordManager: 'SingraVault',
      ai: 'Singra AI',
      openExternal: (label: string) => `Open ${label}`,
    },
    serverSelector: {
      switchFailed: 'Failed to switch server.',
      noServer: 'No Server',
      selectServer: 'Select Server',
      active: 'active',
    },
    languageSelector: {
      languageSet: (label: string) => `Language set to ${label}`,
      changeFailed: 'Failed to change language.',
      active: 'active',
    },
    common: {
      unexpectedError: 'An unexpected error occurred.',
      authenticationRequired: 'Authentication required. Please log in again.',
      permissionDenied: 'Permission denied. You do not have the required permissions for this action.',
      resourceNotFound: 'Resource not found.',
      invalidJsonResponse: 'Invalid JSON response from server.',
    },
    taskConsole: {
      credentialsRequired: 'Steam credentials required. Please check your config.',
      actionFailedCode: (code: number | string | undefined) => `Action failed with code ${code ?? 'unknown'}`,
      errorPrefix: 'Error',
      actionCompleted: 'Action completed.',
      summaryPrefix: 'Summary',
      initializing: 'Initializing task...',
      statusQueued: 'Queued',
      statusRunning: 'in Progress',
      statusFailed: 'Failed',
      statusCompleted: 'Completed',
      waitingForWorker: 'Waiting for worker...',
      dragToReorderAria: 'Drag to reorder',
    },
    loginPage: {
      credentialsRequired: 'Username and password are required.',
      loginFailed: 'Login failed.',
      invalidTwoFactorCode: 'Invalid 2FA code.',
      twoFactorTitle: 'Two-factor authentication',
      panelTitle: 'Server Administration Panel',
      username: 'Username',
      password: 'Password',
      hidePassword: 'Hide password',
      showPassword: 'Show password',
      signIn: 'Sign in',
      signingIn: 'Signing in...',
      twoFactorLabel: 'Authenticator or backup code',
      twoFactorPlaceholder: '123456 or ABCD-EFGH',
      twoFactorHelp: 'Enter the 6-digit authenticator code or one of your backup codes.',
      verify: 'Verify',
      verifying: 'Verifying...',
      backToLogin: 'Back to login',
      heroTitle: 'Self-Hosted Control',
      heroDescription: 'Manage your Conan Exiles dedicated server - backups, restarts, workshop mods and more - from one panel.',
      featureServerControl: 'Server Control',
      featureAutoRestart: 'Auto-Restart',
      featureBackups: 'Backups',
      featureWorkshopMods: 'Workshop Mods',
      featureAuditLog: 'Audit Log',
    },
    setupPage: {
      loadFailed: 'Failed to load setup status. Please refresh the page.',
      usernameRequired: 'Username is required.',
      passwordTooShort: 'Password must be at least 8 characters.',
      passwordsDoNotMatch: 'Passwords do not match.',
      setupFailed: 'Setup failed.',
      subtitle: 'Initial Setup - Create Owner Account',
      username: 'Username',
      password: 'Password',
      passwordPlaceholder: 'Min. 8 characters',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Repeat password',
      hidePassword: 'Hide password',
      showPassword: 'Show password',
      hideConfirmPassword: 'Hide confirm password',
      showConfirmPassword: 'Show confirm password',
      createOwner: 'Create Owner Account',
      creatingAccount: 'Creating account...',
      appearsOnce: 'This screen only appears once - when no accounts exist yet.',
      heroTitle: 'First-Time Setup',
      heroDescription: 'Create your owner account to get started. You can manage additional accounts later.',
    },
    console: {
      title: 'Live Console',
      waiting: 'Waiting for log output...',
      noServer: 'No server selected. Choose a server first.',
      sourceLog: 'RPT Log',
      sourceTmux: 'Tmux',
      sourceTmuxSession: 'Tmux Session',
      filterPlaceholder: 'Filter...',
      filterAria: 'Filter console output',
      jumpToBottom: 'Jump to bottom',
      clearBuffer: 'Clear buffer',
      downloadLogs: 'Download logs',
      idle: 'Idle',
      connecting: 'Connecting...',
      connected: 'Connected',
      reconnecting: 'Reconnecting...',
      error: 'Error',
      disconnected: 'Disconnected',
      reconnect: 'Reconnect',
      lines: (count: number) => `${count.toLocaleString()} lines`,
      filteredLines: (filtered: number, total: number) =>
        `${filtered.toLocaleString()} / ${total.toLocaleString()} lines`,
      authFailed: 'Authentication failed. Please refresh the page.',
      tokenFailed: 'Failed to obtain console token. Are you still logged in?',
    },
    dashboard: {
      actionStarted: (label: string) => `${label} started. Progress is shown below.`,
      actionFinished: (label: string) => `${label} finished.`,
      loadServersFailed: 'Failed to load servers',
      loadServersHelp: 'Could not retrieve server list. Please refresh the page.',
      noServersTitle: 'No servers found',
      noServersDescription: 'Please create or migrate a server to get started.',
      goToServers: 'Go to Servers',
      loadDashboardFailed: 'Failed to load dashboard',
      loadDashboardHelp: 'Failed to load dashboard data.',
      bridgeError: 'Bridge Error',
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first. Server actions stay disabled until an active server is chosen.',
      steamCredentialsTitle: 'Steam Credentials Required',
      steamCredentialsHelp: 'This command requires a valid steamlogin and password in',
      activeServer: 'Active Server',
      online: 'Online',
      offline: 'Offline',
      installed: 'Installed',
      notInstalled: 'Not Installed',
      update: 'Update',
      installServer: 'Install Server',
      service: 'Service',
      database: 'Database',
      serverActions: 'Server Actions',
      installFirst: 'Install the Conan Exiles server first to enable these actions.',
      start: 'Start',
      stop: 'Stop',
      restart: 'Restart',
      validate: 'Validate',
      workshop: 'Workshop',
      backup: 'Backup',
      dangerZone: 'Danger Zone',
      wipeServerData: 'Wipe Server Data',
      wipeTitle: 'Wipe server data?',
      wipeDescription: 'This permanently deletes all server data. Type',
      wipeConfirm: 'Confirm Wipe',
      cancel: 'Cancel',
      restartSchedule: 'Restart Schedule',
      mode: 'Mode',
      summary: 'Summary',
      noScheduleData: 'No schedule data.',
      configureSchedule: 'Configure schedule',
      recentBackups: 'Recent Backups',
      allBackups: 'All backups',
      timestamp: 'Timestamp',
      mission: 'Save',
      profile: 'Profile',
      present: 'Present',
      missing: 'Missing',
      noBackupRuns: 'No backup runs found.',
      workshopMods: 'Workshop Mods',
      config: 'Config',
      configuredMods: 'Configured mods',
      noWorkshopData: 'No workshop data.',
      auditLog: 'Audit Log',
      time: 'Time',
      user: 'User',
      action: 'Action',
      status: 'Status',
      noAuditEntries: 'No audit entries yet.',
      schedulerWarningTitle: 'Scheduler unavailable',
      schedulerWarningDescription: (serviceName: string) =>
        `Scheduled tasks are configured, but ${serviceName} is not active.`,
      ufwRulesTitle: 'Required UFW Rules',
      ufwRulesDesc: 'To allow player connections, you must open these ports on your host\'s firewall using the following commands:',
      ufwRulesNotice: 'Note: The panel does not automatically modify your firewall for security reasons.',
      portInfoTitle: 'Active Server Ports',
    },
    backups: {
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first before creating or restoring backups.',
      errorTitle: 'Error',
      loadFailed: 'Failed to load backups.',
      createTitle: 'Create Backup',
      createDescription: 'Runs the Bash core backup workflow. Stores a timestamped archive under',
      createNow: 'Create Backup Now',
      restoreTitle: 'Restore Backup',
      restoreDescription: 'Stops the server, extracts the selected backup, and restarts. Confirmation required.',
      inventoryTitle: 'Backup Inventory',
      runsFound: (count: number) => `${count} runs found`,
      missionFiles: 'Save Files',
      profileFiles: 'Profile Files',
      noRuns: 'No backup runs found. Create your first backup above.',
      selectServerInventory: 'Select a server to view its backup inventory.',
      timestamp: 'Timestamp',
      restoreDialogTitle: 'Restore backup',
      restoreDialogDescription: 'Select a backup timestamp and type',
      restoreDialogSuffix: 'to confirm. This will overwrite current server data.',
      restoreDialogAction: 'Restore',
      restoreDialogSelect: 'Select backup',
      restoreDialogPlaceholder: 'RESTORE',
      restoreSuccess: 'Backup restored successfully.',
      restoreFailed: 'Restore failed.',
      createSuccess: 'Backup created successfully.',
      createFailed: 'Backup creation failed.',
      cancel: 'Cancel',
    },
    autorestart: {
      currentSchedule: 'Current Schedule',
      mode: 'Mode',
      summary: 'Summary',
      interval: 'Interval',
      scheduledTimes: 'Scheduled Times',
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first before configuring auto-restarts.',
      errorTitle: 'Error',
      configureTitle: 'Configure Schedule',
      configureDescription: 'Choose a restart mode and save. Changes take effect immediately via cron.',
      fixedTimes: 'Fixed Times',
      intervalTab: 'Interval',
      disable: 'Disable',
      restartTimesLabel: 'Restart times (24h, space-separated)',
      restartTimesHelp: 'Example:',
      restartTimesHelpSuffix: 'restarts 4 times daily.',
      saveFixedTimes: 'Save Fixed Times',
      everyNHours: 'Every N hours',
      validValuesPrefix: 'Valid values:',
      validValuesSuffix: 'restarts at 00:00, 08:00, 16:00.',
      saveInterval: 'Save Interval',
      disableHelp: 'Removes all cron entries. The server continues running but will not restart automatically.',
      disableButton: 'Disable Auto-Restarts',
      updateSuccess: 'Auto-restart settings updated.',
      updateFailed: 'Update failed.',
      invalidInterval: (values: string) => `Interval must be one of: ${values}`,
      schedulerWarningTitle: 'Scheduler unavailable',
      schedulerWarningDescription: 'Saved settings exist, but cron is not active.',
    },
    mods: {
      title: 'Mod Management',
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first before managing workshop mods.',
      loadFailedTitle: 'Failed to load mods',
      loadFailedDescription: 'Could not fetch mod list.',
      tableName: 'Name',
      tableWorkshopId: 'Workshop ID',
      tableStatus: 'Status',
      tableClient: 'Client',
      tableServer: 'Server',
      installedTab: 'Installed Mods',
      workshopBrowserTab: 'Workshop Browser',
      manualTab: 'Manual Add',
      installedTitle: 'Installed Mods',
      installedDescription: 'Mods listed in workshop.cfg. Toggle Client/Server to control which mods are loaded at server start. Click Install / Update to download newly added mods.',
      workshopBrowserTitle: 'Workshop Browser',
      workshopBrowserDescription: 'Search the Steam Workshop for Conan Exiles mods and add them with one click. Requires a Steam Web API key in panel/.env.',
      manualTitle: 'Manual Add',
      manualDescription: 'Enter a Steam Workshop mod ID or URL directly, without using the browser search.',
      countLabel: (count: number) => `${count} mod${count !== 1 ? 's' : ''} in workshop.cfg`,
      checkedAgo: (value: string) => `Checked ${value}`,
      updateOutdated: (count: number) => `Update outdated (${count})`,
      checkForUpdates: 'Check for Updates',
      installUpdate: 'Install / Update',
      waitingTaskTitle: 'Waiting for workshop task',
      waitingTaskDescription: 'The panel has not started a workshop action yet.',
      completedTitle: 'Workshop completed',
      completedDescription: 'All selected mods are ready.',
      failedTitle: 'Workshop failed',
      failedDescription: 'The workshop task ended with an error.',
      finishingTitle: 'Finishing setup',
      finishingDescription: 'Writing config changes and syncing keys.',
      linuxPrepTitle: 'Preparing Linux files',
      linuxPrepDescription: 'Normalizing downloaded mod files.',
      downloadingTitle: 'Downloading workshop mods',
      downloadingDescription: 'SteamCMD is downloading the selected mods.',
      checkingTitle: 'Checking installed mods',
      checkingDescription: 'Comparing workshop.cfg with installed workshop content.',
      startingTitle: 'Starting workshop task',
      startingDescription: 'Preparing Steam workshop actions.',
      updateTriggered: 'Update triggered. Checking status again…',
      workshopRunningHelp: 'The list below stays available while SteamCMD works in the background.',
      workshopFailedHelp: 'The workshop task ended early. Check the last log lines below.',
      workshopFinishedHelp: 'Workshop action finished.',
      noModsConfigured: 'No mods configured yet.',
      noModsConfiguredHelp: 'Search the Workshop tab to add mods.',
      dragToReorder: 'Drag to reorder',
      statusUpdate: 'Update',
      upToDate: 'Up to date',
      running: 'Running',
      failedStatus: 'Failed',
      completed: 'Completed',
      dependencyCheckPrefix: 'Dependency check',
      toggleClient: (name: string) => `Toggle client mod ${name}`,
      toggleServer: (name: string) => `Toggle server mod ${name}`,
      toggleSuccess: (mode: 'client' | 'server', enabled: boolean) =>
        `Mod ${enabled ? 'enabled' : 'disabled'} as ${mode}-mod.`,
      removed: 'Mod removed.',
      removeTitle: 'Remove mod?',
      removeDescriptionPrefix: 'Remove',
      removeDescriptionSuffix: 'from workshop.cfg? This also disables it in config.ini. Downloaded mod files are deleted, but shared keys remain in place.',
      cancel: 'Cancel',
      remove: 'Remove',
      autoupdateTitle: 'Auto Mod Update',
      autoupdateDescription: 'Periodically check Steam for mod updates in the background (via cron).',
      autoupdateToggle: 'Enable auto mod update',
      autoupdateEvery: 'Check every',
      autoupdateSave: 'Save',
      autoupdateEnabledSuccess: (label: string) => `Auto-update set to every ${label}.`,
      autoupdateDisabledSuccess: 'Auto-update disabled.',
      schedulerWarningTitle: 'Scheduler unavailable',
      schedulerWarningDescription: (serviceName: string) => `${serviceName} is not active.`,
      workshopStarted: 'Workshop task started. Progress is shown below.',
      searchPlaceholder: 'Search Conan Exiles Workshop mods…',
      searchButton: 'Search',
      searchHelp: 'Search by workshop title. The panel automatically checks dependencies when available.',
      noResults: 'No results found.',
      subscribers: (count: number) => `${count.toLocaleString()} subscribers`,
      added: 'Added',
      loading: 'Loading…',
      add: 'Add',
      addModTitle: 'Add mod',
      addModDescription: 'Choose an internal folder name for',
      addModDescriptionSuffix: 'This becomes the @name used in config.ini. The panel keeps the original name structure and only lowercases it.',
      modFolderName: 'Mod folder name',
      addToWorkshop: 'Add to workshop.cfg',
      dependenciesDetectedTitle: 'Required dependencies detected',
      dependenciesDetectedDescription: (title: string, count: number) => `${title} requires ${count} dependenc${count === 1 ? 'y' : 'ies'}. All will be added to workshop.cfg.`,
      alreadyAdded: 'Already added',
      mainMod: 'main mod',
      addMods: (count: number) => `Add ${count} mods`,
      manualHelp: 'Paste a Steam Workshop mod ID or URL to add it directly without searching.',
      modIdOrUrl: 'Mod ID or Workshop URL',
      modIdPlaceholder: 'e.g. 1559212036 or steamcommunity.com/...?id=...',
      alreadyInWorkshop: 'This mod is already in workshop.cfg.',
      folderName: 'Folder name',
      folderNamePlaceholder: 'e.g. cf',
      folderNameHelp: 'Will be used as',
      storedAsHelp: 'Will be stored as',
      storedInConfigAndWorkshop: 'in config.ini and workshop.cfg.',
      folderNameHelpSuffix: 'in config.ini. Existing spaces and punctuation stay intact, only unsafe separators are removed.',
      steamApiMissingTitle: 'Steam API key not configured',
      searchFailedTitle: 'Search failed',
      searchFailedDescription: 'Could not reach Steam API.',
      searchPrompt: 'Enter a search term to browse Steam Workshop.',
      dependenciesVerificationFailed: 'Dependencies could not be verified automatically.',
      addFailed: 'Failed to add mod.',
      unknownError: 'unknown error',
      addedToWorkshopCount: (count: number) => `${count} mod${count === 1 ? '' : 's'} added to workshop.cfg.`,
      autoInstalledDependencies: (count: number, names: string) =>
        `Also auto-installed ${count} extra dependenc${count === 1 ? 'y' : 'ies'}: ${names}`,
      couldNotVerifyDependencies: 'Could not verify dependencies',
      analysisTitle: 'Mod Analysis',
      analysisDescription: 'Shows where each mod comes from, highlights conflicts and previews what the workshop sync would do.',
      runAnalysis: 'Analyze Mods',
      runDryRun: 'Workshop Dry Run',
      analysisConflictSummary: (count: number) => `${count} conflict${count === 1 ? '' : 's'} detected across configured mods.`,
      analysisDependencyWarning: 'Steam dependency metadata could not be fully verified.',
      dryRunReady: 'Dry run ready.',
      dryRunNoChanges: 'No workshop changes are currently expected.',
      dryRunChangeCount: (count: number) => `${count} workshop action${count === 1 ? '' : 's'} expected.`,
      source_workshop_cfg: 'workshop.cfg',
      source_config_client: 'config.ini (client)',
      source_config_server: 'config.ini (server)',
      source_dependency: 'dependency',
      dryRun_install: 'Install',
      dryRun_update: 'Update',
      dryRun_relink: 'Relink',
      dryRun_remove_symlink: 'Remove stale symlink',
      dryRunReason_install: 'Workshop content is missing.',
      dryRunReason_update: 'Steam reports a newer workshop timestamp.',
      dryRunReason_relink: 'Symlink is missing or points to the wrong target.',
      dryRunReason_remove_symlink: 'Symlink exists locally but the mod is no longer configured.',
      straySymlinksTitle: 'Stray Symlinks',
      configOnlyModsTitle: 'Config-Only Entries',
      dependenciesTitle: 'Dependencies',
      requiredByTitle: 'Required By',
      conflict_duplicate_id: 'This Workshop ID appears more than once in workshop.cfg.',
      conflict_duplicate_name: 'This mod name appears more than once in workshop.cfg.',
      conflict_missing_install: 'Workshop content is missing for this mod.',
      conflict_missing_symlink: 'The @mod symlink is missing from serverfiles.',
      conflict_symlink_target_mismatch: 'The @mod symlink points to a different target than this mod ID.',
    },
    accountPage: {
      title: 'Account settings',
      loggedInAs: 'Logged in as',
      changePasswordTitle: 'Change password',
      changePasswordDescription: 'Update your login password.',
      currentPassword: 'Current password',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      minPassword: 'At least 8 characters required.',
      passwordMismatch: 'Passwords do not match.',
      updatePassword: 'Update password',
      passwordChanged: 'Password changed successfully.',
      passwordChangeFailed: 'Failed to change password.',
      setup2faTitle: 'Set up two-factor authentication',
      setup2faDescription: 'Scan the QR code with your authenticator app, then enter the 6-digit code to confirm. You can download backup codes immediately afterwards.',
      cannotScan: 'Cannot scan? Enter this code manually:',
      scannedCode: 'I scanned the code',
      verificationCode: 'Verification code',
      back: 'Back',
      confirm: 'Confirm',
      enable2fa: 'Enable 2FA',
      disable2faTitle: 'Disable two-factor authentication',
      disable2faDescription: 'Enter your current password and a live authenticator code to confirm. Backup codes cannot disable 2FA.',
      authenticatorCode: 'Authenticator code',
      disable2fa: 'Disable 2FA',
      twoFactorTitle: 'Two-factor authentication',
      enabled: 'Enabled',
      twoFactorDescription: 'Add an extra layer of security to your account using a TOTP authenticator app.',
      activeOnAccount: '2FA is currently active on your account.',
      backupCodes: 'Backup codes',
      backupCodesDownload: 'Download your one-time backup codes now and store them safely.',
      backupCodesRemaining: (count: number) => `${count} unused backup code(s) remaining.`,
      downloadOnce: 'Download once',
      downloadSuccess: 'Backup codes downloaded.',
      downloadFailed: 'Failed to download backup codes.',
      twoFactorEnabled: 'Two-factor authentication enabled.',
      twoFactorEnableFailed: 'Failed to enable 2FA.',
      twoFactorDisabled: 'Two-factor authentication disabled.',
      twoFactorDisableFailed: 'Failed to disable 2FA.',
    },
    usersPage: {
      title: 'User Management',
      description: 'Manage panel users and their permissions.',
      addUser: 'Add user',
      createUser: 'Create user',
      createDescription: 'Add a new panel user with specific permissions.',
      username: 'Username',
      email: 'Email',
      emailOptional: 'Email (optional)',
      password: 'Password',
      role: 'Role',
      permissions: 'Permissions',
      accountActive: 'Account active',
      cancel: 'Cancel',
      saveChanges: 'Save changes',
      userCreated: 'User created.',
      userCreateFailed: 'Failed to create user.',
      userUpdated: 'User updated.',
      userUpdateFailed: 'Failed to update user.',
      passwordReset: 'Password reset.',
      passwordResetFailed: 'Failed to reset password.',
      userDeleted: 'User deleted.',
      userDeleteFailed: 'Failed to delete user.',
      editUser: (name: string) => `Edit ${name}`,
      editDescription: 'Modify role, permissions, and active status.',
      resetPassword: (name: string) => `Reset password — ${name}`,
      newPassword: 'New password',
      reset: 'Reset',
      deleteUser: 'Delete user',
      deleteDescription: (name: string) => `Permanently delete ${name}? This cannot be undone.`,
      status: 'Status',
      lastLogin: 'Last login',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      noValue: '—',
      editUserAria: 'Edit user',
      resetPasswordAria: 'Reset user password',
      deleteUserAria: 'Delete user',
      owner: 'Owner',
      admin: 'Admin',
      user: 'User',
      dashboard: 'Dashboard',
      console: 'Console',
      files: 'Files',
      mods: 'Mods',
      backups: 'Backups',
      servers: 'Servers',
      autorestart: 'Autorestart',
      users: 'Users',
    },
    serversPage: {
      error: 'Error',
      loadFailed: 'Failed to load servers.',
      legacyTitle: 'Legacy server layout detected',
      legacyDescription: 'A flat server layout (~/serverfiles) was found. Migrate it to the multi-server format to manage it through this panel.',
      serversTitle: 'Servers',
      serversDescription: 'Manage Conan Exiles server instances. Each server has its own files, mods, and configuration under ~/servers/<name>/.',
      newServer: 'New Server',
      name: 'Name',
      status: 'Status',
      actions: 'Actions',
      active: 'Active',
      inactive: 'Inactive',
      noServers: 'No servers found. Create your first server above.',
      createTitle: 'Create a new server',
      createDescription: 'Enter a unique name for your new Conan Exiles server instance. Only lowercase letters, digits, and hyphens are allowed (e.g. pvp-eu).',
      serverNamePlaceholder: 'e.g. pvp-eu',
      serverNameAria: 'Server name',
      create: 'Create',
      createSuccess: (name: string) => `Server "${name}" created.`,
      createFailed: 'Failed to create server.',
      clone: 'Clone',
      cloneTitle: (name: string) => `Clone server "${name}"`,
      cloneDescription: 'Create a full copy of this server under a new name. Runtime files and scheduled jobs are not copied to the clone.',
      cloneSourceLabel: 'Source server',
      cloneTargetLabel: 'New server name',
      cloneLiveNotice: 'Live cloning is allowed. If the source server is currently running, the clone is created from the current live filesystem state.',
      cloneSameNameError: 'Source and target server names must be different.',
      cloneAction: 'Clone server',
      cloneSuccess: (source: string, name: string) => `Server "${source}" cloned as "${name}".`,
      cloneFailed: 'Failed to clone server.',
      cloneServerAria: (name: string) => `Clone server ${name}`,
      nameError: 'Only lowercase letters, digits, and hyphens. Must start with a letter or digit.',
      nameTooLong: 'Server names must be 64 characters or fewer.',
      deleteTitle: (name: string) => `Delete server "${name}"`,
      deleteDescription: (name: string) => `ALL data for this server will be permanently deleted. This includes server files, backups, mods, and configuration. Type ${name} to confirm.`,
      confirmDeleteAria: (name: string) => `Type ${name} to confirm`,
      deletePermanently: 'Delete permanently',
      deleteSuccess: (name: string) => `Server "${name}" deleted.`,
      deleteFailed: 'Failed to delete server.',
      deleteServerAria: (name: string) => `Delete server ${name}`,
      migrate: 'Migrate…',
      migrateTitle: 'Migrate legacy server layout',
      migrateDescription: 'A flat server layout (~/serverfiles, ~/steamcmd, …) was detected. Choose a name for the migrated server. The files will be moved to ~/servers/<name>/.',
      targetServerName: 'Target server name',
      migrateSuccess: (name: string) => `Legacy server migrated as "${name}".`,
      migrateFailed: 'Migration failed.',
      tabsList: 'Server List',
      tabsPterodactyl: 'Pterodactyl Import',
      pteroImportTitle: 'Import from Pterodactyl',
      pteroImportDesc: 'Scan and import Conan Exiles server volumes directly from a Pterodactyl host directory. Game database (game.db), mod lists and config files are copied; large game binaries (~20 GB) will be clean installed via SteamCMD when the server is first started.',
      pteroScanPath: 'Volumes Root Directory Path',
      pteroScanButton: 'Scan Volumes',
      pteroScanning: 'Scanning volumes...',
      pteroCandidatesTitle: 'Found Server Candidates',
      pteroNoCandidates: 'No Conan Exiles candidate volumes found at the specified path.',
      pteroColVolume: 'Volume ID / Path',
      pteroColServer: 'Server Details',
      pteroColDb: 'Database',
      pteroColMods: 'Mods',
      pteroColAction: 'Action',
      pteroActionMigrate: 'Import Server',
      pteroMigrating: 'Importing...',
      pteroTargetLabel: 'Target Server Name',
      pteroMigrateSuccess: (name: string) => `Server "${name}" successfully imported from Pterodactyl.`,
      pteroMigrateFailed: 'Import failed.',
    },
    files: {
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first before browsing or editing files.',
      cancel: 'Cancel',
      serverRoot: 'server root',
      unsavedChanges: 'You have unsaved changes. Discard them?',
      fileSaved: 'File saved.',
      fileSaveFailed: (detail?: string) => detail ? `Failed to save file: ${detail}` : 'Failed to save file.',
      deleted: 'Deleted.',
      bulkDeleted: (count: number) => `${count} items deleted.`,
      deleteFailed: (detail?: string) => detail ? `Failed to delete: ${detail}` : 'Failed to delete.',
      directoryCreated: 'Directory created.',
      directoryCreateFailed: 'Failed to create directory.',
      directoryExtracted: (name: string) => `Archive extracted to ${name}.`,
      directoryExtractFailed: 'Failed to extract archive.',
      deleteConfirm: (name: string) => `Delete "${name}"?`,
      deleteManyConfirm: (count: number) => `Delete ${count} selected items?`,
      uploadComplete: 'Upload complete.',
      uploadFailed: (detail?: string) => detail ? `Upload failed: ${detail}` : 'Upload failed.',
      uploadFolderComplete: 'Folder upload complete.',
      uploadFolderFailed: (detail?: string) => detail ? `Folder upload failed: ${detail}` : 'Folder upload failed.',
      uploadItemsComplete: (count: number) => `${count} item${count === 1 ? '' : 's'} uploaded.`,
      uploadItemsFailed: (detail?: string) => detail ? `Upload failed: ${detail}` : 'Upload failed.',
      dropUploadLoading: (count: number) => `Uploading ${count} item${count === 1 ? '' : 's'}...`,
      dropUploadReadFailed: 'Could not read the dropped files.',
      invalidFolderName: 'Invalid folder name.',
      invalidRename: 'Invalid name.',
      newFolderTitle: 'Create folder',
      newFolderDescription: 'Create a new folder in the current directory.',
      folderName: 'Folder name',
      createFolder: 'Create folder',
      uploadFile: 'Upload file',
      uploadFolder: 'Upload folder',
      newFolder: 'New folder',
      dropzoneTitle: 'Drag files or folders into this directory.',
      dropzoneDescription: 'Uploads keep their folder structure. Existing names are checked case-insensitively to avoid Linux duplicate paths.',
      dropzoneActive: 'Drop to upload into the current directory',
      loading: 'Loading...',
      loadDirectoryFailed: 'Failed to load directory.',
      delete: 'Delete',
      deleteTitle: 'Delete selected items',
      emptyDirectory: 'Empty directory',
      download: 'Download',
      extractArchive: 'Extract archive',
      rename: 'Rename',
      renamed: (name: string) => `Renamed to ${name}.`,
      renameFailed: (detail?: string) => detail ? `Failed to rename: ${detail}` : 'Failed to rename.',
      renameTitle: 'Rename item',
      renameDescription: 'Enter a new name for the selected file or folder.',
      renameField: 'New name',
      selectedCount: (count: number) => `${count} selected`,
      quickAccess: 'Quick Access',
      clear: 'Clear',
      clearSelection: 'Clear selection',
      renameHotkey: 'Rename (F2)',
      deleteHotkey: 'Delete selected items (Delete)',
      selectEntry: (name: string) => `Select ${name}`,
      closeTab: (name: string) => `Close ${name}`,
      save: 'Save',
      downloadFailed: (detail?: string) => detail ? `Failed to download selection: ${detail}` : 'Failed to download selection.',
      loadFileFailed: 'Failed to load file content.',
      selectFile: 'Select a file to edit',
    },
    configCenter: {
      title: 'Config Center',
      description: 'Quick access for the most important Conan Exiles config files, a structured ServerSettings.ini editor and safe compare/restore workflows.',
      noServerTitle: 'No server selected',
      noServerDescription: 'Select a server first before editing server configuration files.',
      serverConfigTab: 'ServerSettings.ini',
      filesTab: 'Quick Files',
      serverConfigTitle: 'Structured ServerSettings.ini',
      serverConfigDescription: 'Known Conan Exiles settings are grouped below. Unknown or mod-specific lines stay preserved in the custom block.',
      openDocs: 'Open official Conan Exiles config docs',
      reset: 'Reset',
      saveServerConfig: 'Save ServerSettings.ini',
      serverConfigSaved: 'ServerSettings.ini saved.',
      serverConfigSaveFailed: 'ServerSettings.ini could not be saved.',
      customBlockTitle: 'Preserved custom block',
      customBlockDescription: 'Unknown lines, comments and mod-specific entries stay here and are written back unchanged.',
      quickFilesTitle: 'Quick Files',
      quickFilesDescription: 'Jump directly to the files that are edited most often on a Conan Exiles server.',
      quickDirectoriesTitle: 'Quick Directories',
      quickDirectoriesDescription: 'Jump straight into the most relevant Conan Exiles server folders in the file manager.',
      recentTitle: 'Recent Changes',
      recentDescription: 'Recently changed text files in the active server tree.',
      noRecentFiles: 'No recent files found.',
      exists: 'Exists',
      missing: 'Missing',
      openFolder: 'Open folder',
      selectFileTitle: 'Select a file',
      fileEditorDescription: 'Raw editor with compare mode and single-file restore from backups.',
      readOnlyTitle: 'Read-only access',
      readOnlyDescription: 'You can inspect these files, but saving is disabled for your account.',
      compareNone: 'Normal Editor',
      compareSaved: 'Compare with saved',
      compareBackup: 'Compare with backup',
      backupComparePermissionTitle: 'Backup compare unavailable',
      backupComparePermissionDescription: 'You need backup access to compare this file with a backup or restore it.',
      selectBackup: 'Select backup',
      restoreFromBackup: 'Restore this file',
      restoreSuccess: 'File restored from backup.',
      restoreFailed: 'File could not be restored from backup.',
      compareUnavailableTitle: 'Compare unavailable',
      configIniHintTitle: 'Sensitive file',
      configIniHintDescription: 'config.ini can contain Steam credentials. Keep its contents private.',
      speedhackStrict: '1.0 strict',
      speedhackLenient: '10.0 lenient',
      speedhackEnterValue: 'Enter a value between 1 and 10 to enable the range control.',
      speedhackHint: 'Official Conan Exiles server docs define a float range from 1 to 10. Lower values are stricter, higher values are more tolerant.',
    },
  },
  de: {
    appName: 'Conan Exiles Manager',
    setupUnavailable: 'Verbindung zum Panel fehlgeschlagen. Bitte prüfe, ob der Server läuft.',
    pageTitles: {
      dashboard: 'Dashboard',
      servers: 'Serververwaltung',
      backups: 'Backups',
      autorestart: 'Auto-Neustarts',
      console: 'Live-Konsole',
      mods: 'Mods',
      config: 'Config Center',
      files: 'Dateimanager',
      users: 'Benutzer',
      account: 'Konto',
    },
    nav: {
      dashboard: 'Dashboard',
      servers: 'Server',
      backups: 'Backups',
      autorestart: 'Auto-Neustarts',
      mods: 'Mods',
      console: 'Konsole',
      config: 'Config Center',
      files: 'Dateimanager',
      users: 'Benutzer',
    },
    navSections: {
      overview: 'Übersicht',
      operations: 'Betrieb',
      maintenance: 'Wartung',
      administration: 'Verwaltung',
    },
    account: {
      signOut: 'Abmelden',
      logoutFailed: 'Abmelden fehlgeschlagen. Bitte erneut versuchen.',
      expandSidebar: 'Seitenleiste ausklappen',
      collapseSidebar: 'Seitenleiste einklappen',
      account: 'Konto',
    },
    branding: {
      byline: 'Von MauntingStudios',
      company: 'MauntingStudios',
      website: 'Webseite',
      passwordManager: 'SingraVault',
      ai: 'Singra AI',
      openExternal: (label: string) => `${label} öffnen`,
    },
    serverSelector: {
      switchFailed: 'Serverwechsel fehlgeschlagen.',
      noServer: 'Kein Server',
      selectServer: 'Server wählen',
      active: 'aktiv',
    },
    languageSelector: {
      languageSet: (label: string) => `Sprache auf ${label} gesetzt`,
      changeFailed: 'Sprache konnte nicht geändert werden.',
      active: 'aktiv',
    },
    common: {
      unexpectedError: 'Ein unerwarteter Fehler ist aufgetreten.',
      authenticationRequired: 'Authentifizierung erforderlich. Bitte erneut anmelden.',
      permissionDenied: 'Zugriff verweigert. Dir fehlen die erforderlichen Berechtigungen für diese Aktion.',
      resourceNotFound: 'Ressource nicht gefunden.',
      invalidJsonResponse: 'Ungültige JSON-Antwort vom Server.',
    },
    taskConsole: {
      credentialsRequired: 'Steam-Zugangsdaten erforderlich. Bitte prüfe deine Konfiguration.',
      actionFailedCode: (code: number | string | undefined) => `Aktion mit Code ${code ?? 'unbekannt'} fehlgeschlagen`,
      errorPrefix: 'Fehler',
      actionCompleted: 'Aktion abgeschlossen.',
      summaryPrefix: 'Zusammenfassung',
      initializing: 'Task wird initialisiert...',
      statusQueued: 'Warteschlange',
      statusRunning: 'läuft',
      statusFailed: 'fehlgeschlagen',
      statusCompleted: 'abgeschlossen',
      waitingForWorker: 'Warte auf Worker...',
      dragToReorderAria: 'Zum Umordnen ziehen',
    },
    loginPage: {
      credentialsRequired: 'Benutzername und Passwort sind erforderlich.',
      loginFailed: 'Anmeldung fehlgeschlagen.',
      invalidTwoFactorCode: 'Ungültiger 2FA-Code.',
      twoFactorTitle: 'Zwei-Faktor-Authentifizierung',
      panelTitle: 'Serververwaltungs-Panel',
      username: 'Benutzername',
      password: 'Passwort',
      hidePassword: 'Passwort ausblenden',
      showPassword: 'Passwort einblenden',
      signIn: 'Anmelden',
      signingIn: 'Melde an...',
      twoFactorLabel: 'Authenticator- oder Backup-Code',
      twoFactorPlaceholder: '123456 oder ABCD-EFGH',
      twoFactorHelp: 'Gib den 6-stelligen Authenticator-Code oder einen deiner Backup-Codes ein.',
      verify: 'Prüfen',
      verifying: 'Prüfe...',
      backToLogin: 'Zurück zum Login',
      heroTitle: 'Self-Hosted Control',
      heroDescription: 'Verwalte deinen Conan Exiles-Dedicated-Server - Backups, Neustarts, Workshop-Mods und mehr - in einem Panel.',
      featureServerControl: 'Server-Steuerung',
      featureAutoRestart: 'Auto-Neustart',
      featureBackups: 'Backups',
      featureWorkshopMods: 'Workshop-Mods',
      featureAuditLog: 'Audit-Log',
    },
    setupPage: {
      loadFailed: 'Setup-Status konnte nicht geladen werden. Bitte aktualisiere die Seite.',
      usernameRequired: 'Benutzername ist erforderlich.',
      passwordTooShort: 'Das Passwort muss mindestens 8 Zeichen lang sein.',
      passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein.',
      setupFailed: 'Setup fehlgeschlagen.',
      subtitle: 'Ersteinrichtung - Owner-Konto erstellen',
      username: 'Benutzername',
      password: 'Passwort',
      passwordPlaceholder: 'Mindestens 8 Zeichen',
      confirmPassword: 'Passwort bestätigen',
      confirmPasswordPlaceholder: 'Passwort wiederholen',
      hidePassword: 'Passwort ausblenden',
      showPassword: 'Passwort einblenden',
      hideConfirmPassword: 'Bestätigung ausblenden',
      showConfirmPassword: 'Bestätigung einblenden',
      createOwner: 'Owner-Konto erstellen',
      creatingAccount: 'Konto wird erstellt...',
      appearsOnce: 'Dieser Bildschirm erscheint nur einmal - wenn noch keine Konten existieren.',
      heroTitle: 'Ersteinrichtung',
      heroDescription: 'Erstelle dein Owner-Konto für den Start. Weitere Konten kannst du später verwalten.',
    },
    console: {
      title: 'Live-Konsole',
      waiting: 'Warte auf Konsolenausgabe...',
      noServer: 'Kein Server ausgewählt. Bitte zuerst einen Server wählen.',
      sourceLog: 'RPT-Log',
      sourceTmux: 'Tmux',
      sourceTmuxSession: 'Tmux-Sitzung',
      filterPlaceholder: 'Filtern...',
      filterAria: 'Konsolenausgabe filtern',
      jumpToBottom: 'Nach unten springen',
      clearBuffer: 'Puffer leeren',
      downloadLogs: 'Logs herunterladen',
      idle: 'Leerlauf',
      connecting: 'Verbinde...',
      connected: 'Verbunden',
      reconnecting: 'Verbinde erneut...',
      error: 'Fehler',
      disconnected: 'Getrennt',
      reconnect: 'Neu verbinden',
      lines: (count: number) => `${count.toLocaleString()} Zeilen`,
      filteredLines: (filtered: number, total: number) =>
        `${filtered.toLocaleString()} / ${total.toLocaleString()} Zeilen`,
      authFailed: 'Authentifizierung fehlgeschlagen. Bitte Seite neu laden.',
      tokenFailed: 'Console-Token konnte nicht geladen werden. Bist du noch eingeloggt?',
    },
    dashboard: {
      actionStarted: (label: string) => `${label} gestartet. Der Fortschritt wird unten angezeigt.`,
      actionFinished: (label: string) => `${label} abgeschlossen.`,
      loadServersFailed: 'Server konnten nicht geladen werden',
      loadServersHelp: 'Die Serverliste konnte nicht geladen werden. Bitte Seite neu laden.',
      noServersTitle: 'Keine Server gefunden',
      noServersDescription: 'Bitte erstelle oder migriere zuerst einen Server.',
      goToServers: 'Zu Servern',
      loadDashboardFailed: 'Dashboard konnte nicht geladen werden',
      loadDashboardHelp: 'Dashboard-Daten konnten nicht geladen werden.',
      bridgeError: 'Bridge-Fehler',
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen. Server-Aktionen bleiben bis dahin deaktiviert.',
      steamCredentialsTitle: 'Steam-Zugangsdaten erforderlich',
      steamCredentialsHelp: 'Dieser Befehl benötigt gültige steamlogin- und Passwort-Werte in',
      activeServer: 'Aktiver Server',
      online: 'Online',
      offline: 'Offline',
      installed: 'Installiert',
      notInstalled: 'Nicht installiert',
      update: 'Aktualisieren',
      installServer: 'Server installieren',
      service: 'Dienst',
      database: 'Datenbank',
      serverActions: 'Server-Aktionen',
      installFirst: 'Installiere zuerst den Conan Exiles-Server, um diese Aktionen zu aktivieren.',
      start: 'Starten',
      stop: 'Stoppen',
      restart: 'Neustarten',
      validate: 'Prüfen',
      workshop: 'Workshop',
      backup: 'Backup',
      dangerZone: 'Gefahrenbereich',
      wipeServerData: 'Serverdaten löschen',
      wipeTitle: 'Serverdaten löschen?',
      wipeDescription: 'Dadurch werden alle Serverdaten dauerhaft gelöscht. Tippe',
      wipeConfirm: 'Löschen bestätigen',
      cancel: 'Abbrechen',
      restartSchedule: 'Neustartplan',
      mode: 'Modus',
      summary: 'Zusammenfassung',
      noScheduleData: 'Keine Zeitplandaten vorhanden.',
      configureSchedule: 'Zeitplan konfigurieren',
      recentBackups: 'Letzte Backups',
      allBackups: 'Alle Backups',
      timestamp: 'Zeitstempel',
      mission: 'Save',
      profile: 'Profil',
      present: 'Vorhanden',
      missing: 'Fehlt',
      noBackupRuns: 'Keine Backup-Läufe gefunden.',
      workshopMods: 'Workshop-Mods',
      config: 'Konfiguration',
      configuredMods: 'Konfigurierte Mods',
      noWorkshopData: 'Keine Workshop-Daten vorhanden.',
      auditLog: 'Audit-Log',
      time: 'Zeit',
      user: 'Benutzer',
      action: 'Aktion',
      status: 'Status',
      noAuditEntries: 'Noch keine Audit-Einträge.',
      schedulerWarningTitle: 'Scheduler nicht verfügbar',
      schedulerWarningDescription: (serviceName: string) =>
        `Geplante Aufgaben sind konfiguriert, aber ${serviceName} ist nicht aktiv.`,
      ufwRulesTitle: 'Erforderliche UFW-Regeln',
      ufwRulesDesc: 'Um Spieler-Verbindungen zu ermöglichen, müssen Sie diese Ports auf der Firewall Ihres Hosts mit den folgenden Befehlen freigeben:',
      ufwRulesNotice: 'Hinweis: Das Panel ändert Ihre Firewall aus Sicherheitsgründen nicht automatisch.',
      portInfoTitle: 'Aktive Server-Ports',
    },
    backups: {
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen, bevor du Backups erstellst oder wiederherstellst.',
      errorTitle: 'Fehler',
      loadFailed: 'Backups konnten nicht geladen werden.',
      createTitle: 'Backup erstellen',
      createDescription: 'Führt den Backup-Workflow des Bash-Kerns aus. Speichert ein zeitgestempeltes Archiv unter',
      createNow: 'Backup jetzt erstellen',
      restoreTitle: 'Backup wiederherstellen',
      restoreDescription: 'Stoppt den Server, entpackt das ausgewählte Backup und startet anschließend neu. Bestätigung erforderlich.',
      inventoryTitle: 'Backup-Bestand',
      runsFound: (count: number) => `${count} Läufe gefunden`,
      missionFiles: 'Save-Dateien',
      profileFiles: 'Profildateien',
      noRuns: 'Keine Backup-Läufe gefunden. Erstelle oben dein erstes Backup.',
      selectServerInventory: 'Wähle einen Server aus, um dessen Backup-Bestand zu sehen.',
      timestamp: 'Zeitstempel',
      restoreDialogTitle: 'Backup wiederherstellen',
      restoreDialogDescription: 'Wähle einen Backup-Zeitstempel und tippe',
      restoreDialogSuffix: 'zur Bestätigung. Dabei werden die aktuellen Serverdaten überschrieben.',
      restoreDialogAction: 'Wiederherstellen',
      restoreDialogSelect: 'Backup auswählen',
      restoreDialogPlaceholder: 'RESTORE',
      restoreSuccess: 'Backup erfolgreich wiederhergestellt.',
      restoreFailed: 'Wiederherstellung fehlgeschlagen.',
      createSuccess: 'Backup erfolgreich erstellt.',
      createFailed: 'Backup-Erstellung fehlgeschlagen.',
      cancel: 'Abbrechen',
    },
    autorestart: {
      currentSchedule: 'Aktueller Zeitplan',
      mode: 'Modus',
      summary: 'Zusammenfassung',
      interval: 'Intervall',
      scheduledTimes: 'Geplante Zeiten',
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen, bevor Auto-Neustarts konfiguriert werden.',
      errorTitle: 'Fehler',
      configureTitle: 'Zeitplan konfigurieren',
      configureDescription: 'Wähle einen Neustartmodus und speichere ihn. Die Änderungen greifen sofort über Cron.',
      fixedTimes: 'Feste Zeiten',
      intervalTab: 'Intervall',
      disable: 'Deaktivieren',
      restartTimesLabel: 'Neustartzeiten (24h, mit Leerzeichen getrennt)',
      restartTimesHelp: 'Beispiel:',
      restartTimesHelpSuffix: 'startet 4-mal täglich neu.',
      saveFixedTimes: 'Feste Zeiten speichern',
      everyNHours: 'Alle N Stunden',
      validValuesPrefix: 'Gültige Werte:',
      validValuesSuffix: 'startet um 00:00, 08:00 und 16:00 neu.',
      saveInterval: 'Intervall speichern',
      disableHelp: 'Entfernt alle Cron-Einträge. Der Server läuft weiter, wird aber nicht mehr automatisch neu gestartet.',
      disableButton: 'Auto-Neustarts deaktivieren',
      updateSuccess: 'Auto-Neustart-Einstellungen aktualisiert.',
      updateFailed: 'Aktualisierung fehlgeschlagen.',
      invalidInterval: (values: string) => `Intervall muss einer dieser Werte sein: ${values}`,
      schedulerWarningTitle: 'Scheduler nicht verfügbar',
      schedulerWarningDescription: 'Gespeicherte Einstellungen sind vorhanden, aber cron ist nicht aktiv.',
    },
    mods: {
      title: 'Mod-Verwaltung',
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen, bevor Workshop-Mods verwaltet werden.',
      loadFailedTitle: 'Mods konnten nicht geladen werden',
      loadFailedDescription: 'Die Mod-Liste konnte nicht geladen werden.',
      tableName: 'Name',
      tableWorkshopId: 'Workshop-ID',
      tableStatus: 'Status',
      tableClient: 'Client',
      tableServer: 'Server',
      installedTab: 'Installierte Mods',
      workshopBrowserTab: 'Workshop-Browser',
      manualTab: 'Manuell hinzufügen',
      installedTitle: 'Installierte Mods',
      installedDescription: 'Mods aus workshop.cfg. Über Client/Server steuerst du, welche Mods beim Serverstart geladen werden. Mit Install / Update werden neu hinzugefügte Mods heruntergeladen.',
      workshopBrowserTitle: 'Workshop-Browser',
      workshopBrowserDescription: 'Durchsuche den Steam Workshop nach Conan Exiles-Mods und füge sie mit einem Klick hinzu. Benötigt einen Steam Web API Key in panel/.env.',
      manualTitle: 'Manuell hinzufügen',
      manualDescription: 'Gib eine Steam-Workshop-Mod-ID oder URL direkt ein, ohne die Suche zu benutzen.',
      countLabel: (count: number) => `${count} Mod${count !== 1 ? 's' : ''} in workshop.cfg`,
      checkedAgo: (value: string) => `Geprüft ${value}`,
      updateOutdated: (count: number) => `Veraltete aktualisieren (${count})`,
      checkForUpdates: 'Auf Updates prüfen',
      installUpdate: 'Install / Update',
      waitingTaskTitle: 'Warte auf Workshop-Task',
      waitingTaskDescription: 'Das Panel hat noch keine Workshop-Aktion gestartet.',
      completedTitle: 'Workshop abgeschlossen',
      completedDescription: 'Alle ausgewählten Mods sind bereit.',
      failedTitle: 'Workshop fehlgeschlagen',
      failedDescription: 'Der Workshop-Task wurde mit einem Fehler beendet.',
      finishingTitle: 'Abschluss läuft',
      finishingDescription: 'Konfigurationsänderungen und Keys werden synchronisiert.',
      linuxPrepTitle: 'Linux-Dateien vorbereiten',
      linuxPrepDescription: 'Heruntergeladene Mod-Dateien werden normalisiert.',
      downloadingTitle: 'Workshop-Mods werden heruntergeladen',
      downloadingDescription: 'SteamCMD lädt die ausgewählten Mods herunter.',
      checkingTitle: 'Installierte Mods werden geprüft',
      checkingDescription: 'workshop.cfg wird mit dem installierten Workshop-Inhalt verglichen.',
      startingTitle: 'Workshop-Task startet',
      startingDescription: 'Workshop-Aktionen werden vorbereitet.',
      updateTriggered: 'Update ausgelöst. Status wird erneut geprüft…',
      workshopRunningHelp: 'Die Liste unten bleibt sichtbar, während SteamCMD im Hintergrund arbeitet.',
      workshopFailedHelp: 'Der Workshop-Task wurde vorzeitig beendet. Prüfe die letzten Logzeilen unten.',
      workshopFinishedHelp: 'Workshop-Aktion abgeschlossen.',
      noModsConfigured: 'Noch keine Mods konfiguriert.',
      noModsConfiguredHelp: 'Nutze den Workshop-Tab, um Mods hinzuzufügen.',
      dragToReorder: 'Zum Umordnen ziehen',
      statusUpdate: 'Update',
      upToDate: 'Aktuell',
      running: 'Läuft',
      failedStatus: 'Fehlgeschlagen',
      completed: 'Abgeschlossen',
      dependencyCheckPrefix: 'Abhängigkeitsprüfung',
      toggleClient: (name: string) => `Client-Mod ${name} umschalten`,
      toggleServer: (name: string) => `Server-Mod ${name} umschalten`,
      toggleSuccess: (mode: 'client' | 'server', enabled: boolean) =>
        `Mod als ${mode === 'client' ? 'Client' : 'Server'}-Mod ${enabled ? 'aktiviert' : 'deaktiviert'}.`,
      removed: 'Mod entfernt.',
      removeTitle: 'Mod entfernen?',
      removeDescriptionPrefix: 'Entferne',
      removeDescriptionSuffix: 'aus workshop.cfg. Dadurch wird die Mod auch in config.ini deaktiviert. Heruntergeladene Mod-Dateien werden gelöscht, gemeinsame Keys bleiben erhalten.',
      autoupdateTitle: 'Auto Mod Update',
      autoupdateDescription: 'Prüft Steam im Hintergrund regelmäßig auf Mod-Updates (über cron).',
      autoupdateToggle: 'Auto Mod Update aktivieren',
      autoupdateEvery: 'Prüfen alle',
      autoupdateSave: 'Speichern',
      autoupdateEnabledSuccess: (label: string) => `Auto-Update auf alle ${label} gesetzt.`,
      autoupdateDisabledSuccess: 'Auto-Update deaktiviert.',
      schedulerWarningTitle: 'Scheduler nicht verfügbar',
      schedulerWarningDescription: (serviceName: string) => `${serviceName} ist nicht aktiv.`,
      workshopStarted: 'Workshop-Task gestartet. Der Fortschritt wird unten angezeigt.',
      searchPlaceholder: 'Conan Exiles-Workshop-Mods durchsuchen…',
      searchButton: 'Suchen',
      searchHelp: 'Suche nach Workshop-Titeln. Das Panel prüft Abhängigkeiten automatisch, wenn möglich.',
      noResults: 'Keine Ergebnisse gefunden.',
      subscribers: (count: number) => `${count.toLocaleString()} Abonnenten`,
      added: 'Hinzugefügt',
      loading: 'Lädt…',
      add: 'Hinzufügen',
      addModTitle: 'Mod hinzufügen',
      addModDescription: 'Wähle einen internen Ordnernamen für',
      addModDescriptionSuffix: 'Dieser wird als @name in config.ini verwendet. Das Panel behält die ursprüngliche Namensstruktur bei und schreibt nur klein.',
      modFolderName: 'Mod-Ordnername',
      addToWorkshop: 'Zu workshop.cfg hinzufügen',
      dependenciesDetectedTitle: 'Erforderliche Abhängigkeiten erkannt',
      dependenciesDetectedDescription: (title: string, count: number) => `${title} benötigt ${count} Abhängigkeit${count === 1 ? '' : 'en'}. Alle werden zu workshop.cfg hinzugefügt.`,
      alreadyAdded: 'Bereits hinzugefügt',
      mainMod: 'Hauptmod',
      addMods: (count: number) => `${count} Mods hinzufügen`,
      manualHelp: 'Füge eine Steam-Workshop-Mod-ID oder URL direkt hinzu, ohne die Suche zu benutzen.',
      modIdOrUrl: 'Mod-ID oder Workshop-URL',
      modIdPlaceholder: 'z. B. 1559212036 oder steamcommunity.com/...?id=...',
      alreadyInWorkshop: 'Diese Mod ist bereits in workshop.cfg.',
      folderName: 'Ordnername',
      folderNamePlaceholder: 'z. B. cf',
      folderNameHelp: 'Wird als',
      storedAsHelp: 'Wird als',
      storedInConfigAndWorkshop: 'in config.ini und workshop.cfg. gespeichert.',
      folderNameHelpSuffix: 'in config.ini verwendet. Vorhandene Leerzeichen und Satzzeichen bleiben erhalten, nur unsichere Trenner werden entfernt.',
      cancel: 'Abbrechen',
      remove: 'Entfernen',
      steamApiMissingTitle: 'Steam-API-Key nicht konfiguriert',
      searchFailedTitle: 'Suche fehlgeschlagen',
      searchFailedDescription: 'Die Steam-API konnte nicht erreicht werden.',
      searchPrompt: 'Gib einen Suchbegriff ein, um den Steam Workshop zu durchsuchen.',
      dependenciesVerificationFailed: 'Abhängigkeiten konnten nicht automatisch geprüft werden.',
      addFailed: 'Mod konnte nicht hinzugefügt werden.',
      unknownError: 'unbekannter Fehler',
      addedToWorkshopCount: (count: number) => `${count} Mod${count === 1 ? '' : 's'} zu workshop.cfg hinzugefügt.`,
      autoInstalledDependencies: (count: number, names: string) =>
        `Zusätzlich ${count} weitere Abhängigkeit${count === 1 ? '' : 'en'} automatisch installiert: ${names}`,
      couldNotVerifyDependencies: 'Abhängigkeiten konnten nicht geprüft werden',
      analysisTitle: 'Mod-Analyse',
      analysisDescription: 'Zeigt, woher jede Mod kommt, markiert Konflikte und zeigt vorab, was der Workshop-Sync tun würde.',
      runAnalysis: 'Mods analysieren',
      runDryRun: 'Workshop-Dry-Run',
      analysisConflictSummary: (count: number) => `${count} Konflikt${count === 1 ? '' : 'e'} in den konfigurierten Mods erkannt.`,
      analysisDependencyWarning: 'Steam-Abhängigkeitsdaten konnten nicht vollständig geprüft werden.',
      dryRunReady: 'Dry-Run bereit.',
      dryRunNoChanges: 'Aktuell werden keine Workshop-Änderungen erwartet.',
      dryRunChangeCount: (count: number) => `${count} erwartete Workshop-Aktion${count === 1 ? '' : 'en'}.`,
      source_workshop_cfg: 'workshop.cfg',
      source_config_client: 'config.ini (Client)',
      source_config_server: 'config.ini (Server)',
      source_dependency: 'Abhängigkeit',
      dryRun_install: 'Installieren',
      dryRun_update: 'Aktualisieren',
      dryRun_relink: 'Neu verlinken',
      dryRun_remove_symlink: 'Veralteten Symlink entfernen',
      dryRunReason_install: 'Der Workshop-Inhalt fehlt.',
      dryRunReason_update: 'Steam meldet einen neueren Workshop-Zeitstempel.',
      dryRunReason_relink: 'Der Symlink fehlt oder zeigt auf das falsche Ziel.',
      dryRunReason_remove_symlink: 'Der Symlink existiert lokal, die Mod ist aber nicht mehr konfiguriert.',
      straySymlinksTitle: 'Verwaiste Symlinks',
      configOnlyModsTitle: 'Nur in der Config',
      dependenciesTitle: 'Abhängigkeiten',
      requiredByTitle: 'Benötigt von',
      conflict_duplicate_id: 'Diese Workshop-ID kommt mehrfach in workshop.cfg vor.',
      conflict_duplicate_name: 'Dieser Mod-Name kommt mehrfach in workshop.cfg vor.',
      conflict_missing_install: 'Der Workshop-Inhalt für diese Mod fehlt.',
      conflict_missing_symlink: 'Der @mod-Symlink fehlt im serverfiles-Ordner.',
      conflict_symlink_target_mismatch: 'Der @mod-Symlink zeigt auf ein anderes Ziel als diese Mod-ID.',
    },
    accountPage: {
      title: 'Kontoeinstellungen',
      loggedInAs: 'Angemeldet als',
      changePasswordTitle: 'Passwort ändern',
      changePasswordDescription: 'Aktualisiere dein Anmeldepasswort.',
      currentPassword: 'Aktuelles Passwort',
      newPassword: 'Neues Passwort',
      confirmNewPassword: 'Neues Passwort bestätigen',
      minPassword: 'Mindestens 8 Zeichen erforderlich.',
      passwordMismatch: 'Passwörter stimmen nicht überein.',
      updatePassword: 'Passwort aktualisieren',
      passwordChanged: 'Passwort erfolgreich geändert.',
      passwordChangeFailed: 'Passwort konnte nicht geändert werden.',
      setup2faTitle: 'Zwei-Faktor-Authentifizierung einrichten',
      setup2faDescription: 'Scanne den QR-Code mit deiner Authenticator-App und gib danach den 6-stelligen Code zur Bestätigung ein. Direkt danach kannst du Backup-Codes herunterladen.',
      cannotScan: 'Kannst du nicht scannen? Gib diesen Code manuell ein:',
      scannedCode: 'Ich habe den Code gescannt',
      verificationCode: 'Bestätigungscode',
      back: 'Zurück',
      confirm: 'Bestätigen',
      enable2fa: '2FA aktivieren',
      disable2faTitle: 'Zwei-Faktor-Authentifizierung deaktivieren',
      disable2faDescription: 'Gib dein aktuelles Passwort und einen aktuellen Authenticator-Code ein. Backup-Codes können 2FA nicht deaktivieren.',
      authenticatorCode: 'Authenticator-Code',
      disable2fa: '2FA deaktivieren',
      twoFactorTitle: 'Zwei-Faktor-Authentifizierung',
      enabled: 'Aktiv',
      twoFactorDescription: 'Füge deinem Konto mit einer TOTP-Authenticator-App eine zusätzliche Sicherheitsebene hinzu.',
      activeOnAccount: '2FA ist für dein Konto aktuell aktiv.',
      backupCodes: 'Backup-Codes',
      backupCodesDownload: 'Lade deine einmaligen Backup-Codes jetzt herunter und bewahre sie sicher auf.',
      backupCodesRemaining: (count: number) => `${count} ungenutzte Backup-Code(s) verbleibend.`,
      downloadOnce: 'Einmal herunterladen',
      downloadSuccess: 'Backup-Codes heruntergeladen.',
      downloadFailed: 'Backup-Codes konnten nicht heruntergeladen werden.',
      twoFactorEnabled: 'Zwei-Faktor-Authentifizierung aktiviert.',
      twoFactorEnableFailed: '2FA konnte nicht aktiviert werden.',
      twoFactorDisabled: 'Zwei-Faktor-Authentifizierung deaktiviert.',
      twoFactorDisableFailed: '2FA konnte nicht deaktiviert werden.',
    },
    usersPage: {
      title: 'Benutzerverwaltung',
      description: 'Verwalte Panel-Benutzer und ihre Berechtigungen.',
      addUser: 'Benutzer hinzufügen',
      createUser: 'Benutzer erstellen',
      createDescription: 'Füge einen neuen Panel-Benutzer mit spezifischen Berechtigungen hinzu.',
      username: 'Benutzername',
      email: 'E-Mail',
      emailOptional: 'E-Mail (optional)',
      password: 'Passwort',
      role: 'Rolle',
      permissions: 'Berechtigungen',
      accountActive: 'Konto aktiv',
      cancel: 'Abbrechen',
      saveChanges: 'Änderungen speichern',
      userCreated: 'Benutzer erstellt.',
      userCreateFailed: 'Benutzer konnte nicht erstellt werden.',
      userUpdated: 'Benutzer aktualisiert.',
      userUpdateFailed: 'Benutzer konnte nicht aktualisiert werden.',
      passwordReset: 'Passwort zurückgesetzt.',
      passwordResetFailed: 'Passwort konnte nicht zurückgesetzt werden.',
      userDeleted: 'Benutzer gelöscht.',
      userDeleteFailed: 'Benutzer konnte nicht gelöscht werden.',
      editUser: (name: string) => `${name} bearbeiten`,
      editDescription: 'Ändere Rolle, Berechtigungen und Aktiv-Status.',
      resetPassword: (name: string) => `Passwort zurücksetzen — ${name}`,
      newPassword: 'Neues Passwort',
      reset: 'Zurücksetzen',
      deleteUser: 'Benutzer löschen',
      deleteDescription: (name: string) => `${name} dauerhaft löschen? Das kann nicht rückgängig gemacht werden.`,
      status: 'Status',
      lastLogin: 'Letzter Login',
      actions: 'Aktionen',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      noValue: '—',
      editUserAria: 'Benutzer bearbeiten',
      resetPasswordAria: 'Benutzerpasswort zurücksetzen',
      deleteUserAria: 'Benutzer löschen',
      owner: 'Owner',
      admin: 'Admin',
      user: 'Benutzer',
      dashboard: 'Dashboard',
      console: 'Konsole',
      files: 'Dateien',
      mods: 'Mods',
      backups: 'Backups',
      servers: 'Server',
      autorestart: 'Auto-Neustart',
      users: 'Benutzer',
    },
    serversPage: {
      error: 'Fehler',
      loadFailed: 'Server konnten nicht geladen werden.',
      legacyTitle: 'Legacy-Serverlayout erkannt',
      legacyDescription: 'Ein flaches Serverlayout (~/serverfiles) wurde gefunden. Migriere es in das Multi-Server-Format, um es über dieses Panel zu verwalten.',
      serversTitle: 'Server',
      serversDescription: 'Verwalte Conan Exiles-Serverinstanzen. Jeder Server hat eigene Dateien, Mods und Konfigurationen unter ~/servers/<name>/.',
      newServer: 'Neuer Server',
      name: 'Name',
      status: 'Status',
      actions: 'Aktionen',
      active: 'Aktiv',
      inactive: 'Inaktiv',
      noServers: 'Keine Server gefunden. Erstelle oben deinen ersten Server.',
      createTitle: 'Neuen Server erstellen',
      createDescription: 'Gib einen eindeutigen Namen für deine neue Conan Exiles-Serverinstanz ein. Erlaubt sind nur Kleinbuchstaben, Ziffern und Bindestriche (z. B. pvp-eu).',
      serverNamePlaceholder: 'z. B. pvp-eu',
      serverNameAria: 'Servername',
      create: 'Erstellen',
      createSuccess: (name: string) => `Server "${name}" erstellt.`,
      createFailed: 'Server konnte nicht erstellt werden.',
      clone: 'Klonen',
      cloneTitle: (name: string) => `Server "${name}" klonen`,
      cloneDescription: 'Erstellt eine vollständige Kopie dieses Servers unter einem neuen Namen. Laufzeitdateien und Zeitpläne werden nicht in den Klon übernommen.',
      cloneSourceLabel: 'Quellserver',
      cloneTargetLabel: 'Neuer Servername',
      cloneLiveNotice: 'Live-Klonen ist erlaubt. Wenn der Quellserver gerade läuft, wird der Klon aus dem aktuellen Live-Dateisystemstand erstellt.',
      cloneSameNameError: 'Quell- und Zielserver müssen unterschiedliche Namen haben.',
      cloneAction: 'Server klonen',
      cloneSuccess: (source: string, name: string) => `Server "${source}" wurde als "${name}" geklont.`,
      cloneFailed: 'Server konnte nicht geklont werden.',
      cloneServerAria: (name: string) => `Server ${name} klonen`,
      nameError: 'Nur Kleinbuchstaben, Ziffern und Bindestriche. Muss mit Buchstabe oder Ziffer beginnen.',
      nameTooLong: 'Servernamen dürfen höchstens 64 Zeichen lang sein.',
      deleteTitle: (name: string) => `Server "${name}" löschen`,
      deleteDescription: (name: string) => `ALLE Daten für diesen Server werden dauerhaft gelöscht. Dazu gehören Serverdateien, Backups, Mods und Konfiguration. Tippe ${name} zur Bestätigung ein.`,
      confirmDeleteAria: (name: string) => `${name} zur Bestätigung eingeben`,
      deletePermanently: 'Dauerhaft löschen',
      deleteSuccess: (name: string) => `Server "${name}" gelöscht.`,
      deleteFailed: 'Server konnte nicht gelöscht werden.',
      deleteServerAria: (name: string) => `Server ${name} löschen`,
      migrate: 'Migrieren…',
      migrateTitle: 'Legacy-Serverlayout migrieren',
      migrateDescription: 'Ein flaches Serverlayout (~/serverfiles, ~/steamcmd, …) wurde erkannt. Wähle einen Namen für den migrierten Server. Die Dateien werden nach ~/servers/<name>/ verschoben.',
      targetServerName: 'Ziel-Servername',
      migrateSuccess: (name: string) => `Legacy-Server als "${name}" migriert.`,
      migrateFailed: 'Migration fehlgeschlagen.',
      tabsList: 'Server-Liste',
      tabsPterodactyl: 'Pterodactyl-Import',
      pteroImportTitle: 'Aus Pterodactyl importieren',
      pteroImportDesc: 'Scanne und importiere Conan Exiles Server-Volumes direkt aus einem Pterodactyl-Hostverzeichnis. Spieldatenbank (game.db), Mod-Listen und Konfigurationsdateien werden kopiert; große Spiel-Binärdateien (~20 GB) werden beim ersten Start sauber über SteamCMD installiert.',
      pteroScanPath: 'Volume-Root-Verzeichnis-Pfad',
      pteroScanButton: 'Volumes scannen',
      pteroScanning: 'Volumes werden gescannt...',
      pteroCandidatesTitle: 'Gefundene Server-Kandidaten',
      pteroNoCandidates: 'Keine Conan Exiles-Volumes am angegebenen Pfad gefunden.',
      pteroColVolume: 'Volume-ID / Pfad',
      pteroColServer: 'Server-Details',
      pteroColDb: 'Datenbank',
      pteroColMods: 'Mods',
      pteroColAction: 'Aktion',
      pteroActionMigrate: 'Server importieren',
      pteroMigrating: 'Wird importiert...',
      pteroTargetLabel: 'Ziel-Servername',
      pteroMigrateSuccess: (name: string) => `Server "${name}" erfolgreich aus Pterodactyl importiert.`,
      pteroMigrateFailed: 'Import fehlgeschlagen.',
    },
    files: {
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen, bevor Dateien durchsucht oder bearbeitet werden.',
      cancel: 'Abbrechen',
      serverRoot: 'Server-Stamm',
      unsavedChanges: 'Es gibt ungespeicherte Änderungen. Verwerfen?',
      fileSaved: 'Datei gespeichert.',
      fileSaveFailed: (detail?: string) => detail ? `Datei konnte nicht gespeichert werden: ${detail}` : 'Datei konnte nicht gespeichert werden.',
      deleted: 'Gelöscht.',
      bulkDeleted: (count: number) => `${count} Einträge gelöscht.`,
      deleteFailed: (detail?: string) => detail ? `Löschen fehlgeschlagen: ${detail}` : 'Löschen fehlgeschlagen.',
      directoryCreated: 'Ordner erstellt.',
      directoryCreateFailed: 'Ordner konnte nicht erstellt werden.',
      directoryExtracted: (name: string) => `Archiv nach ${name} entpackt.`,
      directoryExtractFailed: 'Archiv konnte nicht entpackt werden.',
      deleteConfirm: (name: string) => `"${name}" löschen?`,
      deleteManyConfirm: (count: number) => `${count} ausgewählte Einträge löschen?`,
      uploadComplete: 'Upload abgeschlossen.',
      uploadFailed: (detail?: string) => detail ? `Upload fehlgeschlagen: ${detail}` : 'Upload fehlgeschlagen.',
      uploadFolderComplete: 'Ordner-Upload abgeschlossen.',
      uploadFolderFailed: (detail?: string) => detail ? `Ordner-Upload fehlgeschlagen: ${detail}` : 'Ordner-Upload fehlgeschlagen.',
      uploadItemsComplete: (count: number) => `${count} Element${count === 1 ? '' : 'e'} hochgeladen.`,
      uploadItemsFailed: (detail?: string) => detail ? `Upload fehlgeschlagen: ${detail}` : 'Upload fehlgeschlagen.',
      dropUploadLoading: (count: number) => `${count} Element${count === 1 ? '' : 'e'} werden hochgeladen...`,
      dropUploadReadFailed: 'Die hereingezogenen Dateien konnten nicht gelesen werden.',
      invalidFolderName: 'Ungültiger Ordnername.',
      invalidRename: 'Ungültiger Name.',
      newFolderTitle: 'Ordner erstellen',
      newFolderDescription: 'Erstelle einen neuen Ordner im aktuellen Verzeichnis.',
      folderName: 'Ordnername',
      createFolder: 'Ordner erstellen',
      uploadFile: 'Datei hochladen',
      uploadFolder: 'Ordner hochladen',
      newFolder: 'Neuer Ordner',
      dropzoneTitle: 'Dateien oder Ordner in dieses Verzeichnis ziehen.',
      dropzoneDescription: 'Die Ordnerstruktur bleibt erhalten. Vorhandene Namen werden case-insensitive geprüft, damit unter Linux keine doppelten Pfade entstehen.',
      dropzoneActive: 'Loslassen, um in das aktuelle Verzeichnis hochzuladen',
      loading: 'Lade...',
      loadDirectoryFailed: 'Verzeichnis konnte nicht geladen werden.',
      delete: 'Löschen',
      deleteTitle: 'Auswahl löschen',
      emptyDirectory: 'Leeres Verzeichnis',
      download: 'Herunterladen',
      extractArchive: 'Archiv entpacken',
      rename: 'Umbenennen',
      renamed: (name: string) => `Umbenannt zu ${name}.`,
      renameFailed: (detail?: string) => detail ? `Umbenennen fehlgeschlagen: ${detail}` : 'Umbenennen fehlgeschlagen.',
      renameTitle: 'Eintrag umbenennen',
      renameDescription: 'Gib einen neuen Namen für die ausgewählte Datei oder den Ordner ein.',
      renameField: 'Neuer Name',
      selectedCount: (count: number) => `${count} ausgewählt`,
      quickAccess: 'Schnellzugriff',
      clear: 'Leeren',
      clearSelection: 'Auswahl leeren',
      renameHotkey: 'Umbenennen (F2)',
      deleteHotkey: 'Auswahl löschen (Entf)',
      selectEntry: (name: string) => `${name} auswählen`,
      closeTab: (name: string) => `${name} schließen`,
      save: 'Speichern',
      downloadFailed: (detail?: string) => detail ? `Auswahl konnte nicht heruntergeladen werden: ${detail}` : 'Auswahl konnte nicht heruntergeladen werden.',
      loadFileFailed: 'Dateiinhalt konnte nicht geladen werden.',
      selectFile: 'Wähle eine Datei zum Bearbeiten aus',
    },
    configCenter: {
      title: 'Config Center',
      description: 'Schnellzugriff auf die wichtigsten Conan Exiles-Konfigurationsdateien, einen strukturierten ServerSettings.ini-Editor und sichere Compare-/Restore-Abläufe.',
      noServerTitle: 'Kein Server ausgewählt',
      noServerDescription: 'Bitte zuerst einen Server auswählen, bevor Server-Konfigurationsdateien bearbeitet werden.',
      serverConfigTab: 'ServerSettings.ini',
      filesTab: 'Quick Files',
      serverConfigTitle: 'Strukturierte ServerSettings.ini',
      serverConfigDescription: 'Bekannte Conan Exiles-Einstellungen sind unten gruppiert. Unbekannte oder mod-spezifische Zeilen bleiben im Custom-Block erhalten.',
      openDocs: 'Offizielle Conan Exiles-Config-Doku öffnen',
      reset: 'Zurücksetzen',
      saveServerConfig: 'ServerSettings.ini speichern',
      serverConfigSaved: 'ServerSettings.ini gespeichert.',
      serverConfigSaveFailed: 'ServerSettings.ini konnte nicht gespeichert werden.',
      customBlockTitle: 'Erhaltener Custom-Block',
      customBlockDescription: 'Unbekannte Zeilen, Kommentare und mod-spezifische Einträge bleiben hier erhalten und werden unverändert zurückgeschrieben.',
      quickFilesTitle: 'Quick Files',
      quickFilesDescription: 'Direkter Zugriff auf die Dateien, die auf einem Conan Exiles-Server am häufigsten bearbeitet werden.',
      quickDirectoriesTitle: 'Quick Directories',
      quickDirectoriesDescription: 'Direkter Sprung in die wichtigsten Conan Exiles-Serverordner im Dateimanager.',
      recentTitle: 'Letzte Änderungen',
      recentDescription: 'Zuletzt geänderte Textdateien im aktiven Serverbaum.',
      noRecentFiles: 'Keine zuletzt geänderten Dateien gefunden.',
      exists: 'Vorhanden',
      missing: 'Fehlt',
      openFolder: 'Ordner öffnen',
      selectFileTitle: 'Datei auswählen',
      fileEditorDescription: 'Raw-Editor mit Compare-Modus und Einzeldatei-Restore aus Backups.',
      readOnlyTitle: 'Nur Lesezugriff',
      readOnlyDescription: 'Du kannst diese Dateien ansehen, aber mit deinem Konto nicht speichern.',
      compareNone: 'Normaler Editor',
      compareSaved: 'Mit gespeichert vergleichen',
      compareBackup: 'Mit Backup vergleichen',
      backupComparePermissionTitle: 'Backup-Vergleich nicht verfügbar',
      backupComparePermissionDescription: 'Du benötigst Backup-Zugriff, um diese Datei mit einem Backup zu vergleichen oder wiederherzustellen.',
      selectBackup: 'Backup auswählen',
      restoreFromBackup: 'Diese Datei wiederherstellen',
      restoreSuccess: 'Datei aus Backup wiederhergestellt.',
      restoreFailed: 'Datei konnte nicht aus dem Backup wiederhergestellt werden.',
      compareUnavailableTitle: 'Vergleich nicht verfügbar',
      configIniHintTitle: 'Sensible Datei',
      configIniHintDescription: 'config.ini kann Steam-Zugangsdaten enthalten. Halte ihren Inhalt privat.',
      speedhackStrict: '1.0 streng',
      speedhackLenient: '10.0 tolerant',
      speedhackEnterValue: 'Gib einen Wert zwischen 1 und 10 ein, um den Regler zu aktivieren.',
      speedhackHint: 'Die offizielle Conan Exiles-Serverdoku definiert einen Float-Bereich von 1 bis 10. Niedrige Werte sind strenger, hohe Werte toleranter.',
    },
  },
} as const

type UiCopy = (typeof UI_COPY)[UiLanguage]

const UiLanguageContext = createContext<{ language: UiLanguage; copy: UiCopy }>({
  language: 'en',
  copy: UI_COPY.en,
})

function normalizeLanguage(value: string | undefined): UiLanguage {
    return value === 'de' ? 'de' : 'en'
}

export function getUiCopy(language: UiLanguage) {
    return UI_COPY[language]
}

export function UiLanguageProvider({ children }: { children: ReactNode }) {
  const { data: serversData } = useQuery({
    queryKey: ['servers'],
    queryFn: serversApi.list,
    staleTime: 30_000,
  })
  const hasCurrentServer = Boolean(serversData?.current)
  const currentServer = serversData?.current ?? null
  const { data: languageData } = useQuery({
    queryKey: ['language', currentServer],
    queryFn: languageApi.get,
    staleTime: 60_000,
    enabled: hasCurrentServer,
  })
  const language = normalizeLanguage(languageData?.language)

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language
    }
  }, [language])

  return (
    <UiLanguageContext.Provider value={{ language, copy: UI_COPY[language] }}>
      {children}
    </UiLanguageContext.Provider>
  )
}

export function useUiLanguage() {
  return useContext(UiLanguageContext)
}
