import sys
import json
import re
from pathlib import Path

tag = sys.argv[1].lstrip("v") if len(sys.argv) > 1 and sys.argv[1] else "4.0.0"

conf_path = Path("smart-system/src-tauri/tauri.conf.json")
if conf_path.exists():
    data = json.loads(conf_path.read_text(encoding="utf-8"))
    data["version"] = tag
    conf_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

cargo_path = Path("smart-system/src-tauri/Cargo.toml")
if cargo_path.exists():
    content = cargo_path.read_text(encoding="utf-8")
    content = re.sub(r'(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"', rf'\g<1>"{tag}"', content, flags=re.MULTILINE)
    cargo_path.write_text(content, encoding="utf-8")

frontend_pkg = Path("frontend/package.json")
if frontend_pkg.exists():
    pkg_data = json.loads(frontend_pkg.read_text(encoding="utf-8"))
    pkg_data["version"] = tag
    frontend_pkg.write_text(json.dumps(pkg_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

frontend_lock = Path("frontend/package-lock.json")
if frontend_lock.exists():
    lock_data = json.loads(frontend_lock.read_text(encoding="utf-8"))
    lock_data["version"] = tag
    if "packages" in lock_data and "" in lock_data["packages"]:
        lock_data["packages"][""]["version"] = tag
    frontend_lock.write_text(json.dumps(lock_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# Android tauri.properties synchronisieren
for prop_dir in [
    Path("smart-system/src-tauri/gen/android/app"),
    Path("browser/src-tauri/gen/android/app"),
]:
    prop_path = prop_dir / "tauri.properties"
    if prop_path.exists():
        parts = [int(p) for p in re.findall(r'\d+', tag)]
        major = parts[0] if len(parts) > 0 else 5
        minor = parts[1] if len(parts) > 1 else 0
        patch = parts[2] if len(parts) > 2 else 0
        version_code = major * 1000000 + minor * 1000 + patch
        prop_lines = [
            "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
            f"tauri.android.versionName={tag}",
            f"tauri.android.versionCode={version_code}\n",
        ]
        prop_path.write_text("\n".join(prop_lines), encoding="utf-8")
        print(f"Synchronized Android tauri.properties in {prop_dir}: versionName={tag}, versionCode={version_code}")

# Recovery App synchronisieren
rec_conf = Path("recovery/src-tauri/tauri.conf.json")
if rec_conf.exists():
    rec_data = json.loads(rec_conf.read_text(encoding="utf-8"))
    rec_data["version"] = tag
    rec_conf.write_text(json.dumps(rec_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

rec_cargo = Path("recovery/src-tauri/Cargo.toml")
if rec_cargo.exists():
    rec_content = rec_cargo.read_text(encoding="utf-8")
    rec_content = re.sub(r'(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"', rf'\g<1>"{tag}"', rec_content, flags=re.MULTILINE)
    rec_cargo.write_text(rec_content, encoding="utf-8")

# Maunting Secure Browser: dieselbe Version wie MSM und MSS (gemeinsamer v*-Tag)
browser_conf = Path("browser/src-tauri/tauri.conf.json")
if browser_conf.exists():
    browser_data = json.loads(browser_conf.read_text(encoding="utf-8"))
    browser_data["version"] = tag
    browser_conf.write_text(json.dumps(browser_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

browser_cargo = Path("browser/src-tauri/Cargo.toml")
if browser_cargo.exists():
    browser_content = browser_cargo.read_text(encoding="utf-8")
    browser_content = re.sub(r'(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"', rf'\g<1>"{tag}"', browser_content, flags=re.MULTILINE)
    browser_cargo.write_text(browser_content, encoding="utf-8")

browser_pkg = Path("browser/package.json")
if browser_pkg.exists():
    browser_pkg_data = json.loads(browser_pkg.read_text(encoding="utf-8"))
    browser_pkg_data["version"] = tag
    browser_pkg.write_text(json.dumps(browser_pkg_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

browser_lock = Path("browser/package-lock.json")
if browser_lock.exists():
    b_lock_data = json.loads(browser_lock.read_text(encoding="utf-8"))
    b_lock_data["version"] = tag
    if "packages" in b_lock_data and "" in b_lock_data["packages"]:
        b_lock_data["packages"][""]["version"] = tag
    browser_lock.write_text(json.dumps(b_lock_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# Cargo.lock Dateien synchronisieren
cargo_locks = [
    (Path("smart-system/src-tauri/Cargo.lock"), "maunting-smart-system"),
    (Path("browser/src-tauri/Cargo.lock"), "maunting-secure-browser"),
    (Path("recovery/src-tauri/Cargo.lock"), "msm-backup-recovery"),
]
for clock_path, pkg_name in cargo_locks:
    if clock_path.exists():
        content = clock_path.read_text(encoding="utf-8")
        pattern = rf'(\[\[package\]\]\s*name\s*=\s*"{re.escape(pkg_name)}"\s*version\s*=\s*)"[^"]+"'
        content = re.sub(pattern, rf'\g<1>"{tag}"', content)
        clock_path.write_text(content, encoding="utf-8")

# Backend /api/version synchronisieren
backend_main = Path("backend/main.py")
if backend_main.exists():
    main_content = backend_main.read_text(encoding="utf-8")
    main_content = re.sub(r'("version":\s*)"[^"]+"', rf'\g<1>"{tag}"', main_content)
    backend_main.write_text(main_content, encoding="utf-8")

backend_test_version = Path("backend/tests/test_app_version.py")
if backend_test_version.exists():
    test_content = backend_test_version.read_text(encoding="utf-8")
    test_content = re.sub(r'(assert res\["version"\] ==\s*)"[^"]+"', rf'\g<1>"{tag}"', test_content)
    backend_test_version.write_text(test_content, encoding="utf-8")

print(f"Synchronized all application versions to {tag}")
