import sys
import json
import re
from pathlib import Path

tag = sys.argv[1].lstrip("v") if len(sys.argv) > 1 and sys.argv[1] else "4.0.0"

conf_path = Path("smart-system/src-tauri/tauri.conf.json")
if conf_path.exists():
    data = json.loads(conf_path.read_text(encoding="utf-8"))
    data["version"] = tag
    conf_path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

cargo_path = Path("smart-system/src-tauri/Cargo.toml")
if cargo_path.exists():
    content = cargo_path.read_text(encoding="utf-8")
    content = re.sub(r'(^\[package\][\s\S]*?^version\s*=\s*)"[^"]+"', rf'\g<1>"{tag}"', content, flags=re.MULTILINE)
    cargo_path.write_text(content, encoding="utf-8")

frontend_pkg = Path("frontend/package.json")
if frontend_pkg.exists():
    pkg_data = json.loads(frontend_pkg.read_text(encoding="utf-8"))
    pkg_data["version"] = tag
    frontend_pkg.write_text(json.dumps(pkg_data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

# Android tauri.properties synchronisieren
prop_path = Path("smart-system/src-tauri/gen/android/app/tauri.properties")
if prop_path.exists():
    parts = [int(p) for p in re.findall(r'\d+', tag)]
    major = parts[0] if len(parts) > 0 else 4
    minor = parts[1] if len(parts) > 1 else 0
    patch = parts[2] if len(parts) > 2 else 0
    # Eindeutiger, monoton steigender Android-VersionCode
    version_code = major * 1000000 + minor * 1000 + patch
    prop_lines = [
        "// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
        f"tauri.android.versionName={tag}",
        f"tauri.android.versionCode={version_code}\n",
    ]
    prop_path.write_text("\n".join(prop_lines), encoding="utf-8")
    print(f"Synchronized Android tauri.properties: versionName={tag}, versionCode={version_code}")

print(f"Synchronized smart-system version to {tag}")
